<a href="https://colab.research.google.com/github/RishabKr15/CBTC/blob/main/Data_Manipulation_with_Pandas_%5BComplete%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Topics
1. Series and dataframes
2. Setting up the directory : (OS Package)
3. Loading different file formats
4. Basic Inspection of dataset
5. Indexing & Slicing
6. Creating new columns, renaming & droping
6. Handling Missing Values
7. Sorting & Handling Duplicates
8. Aggregating Data
9. Joining Datasets
10. .replace(),.apply()
11. Dealing with Strings, Datetime & Json data in column
12. Reshaping data
13. Caching & Parallelization
14. Writing data

In [ ]:
#Import package
import pandas as pd

### Series and Dataframe

In [ ]:
# Series: A series is essentially a column (1-D data)
# Data Frame: A DataFrame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns.
# Pandas DataFrame consists of three principal components, the data, rows, and columns.

In [ ]:
# Series
s1 = pd.Series([28, 20, 32, 40])
s2 = pd.Series(['John','David','Reva','Grahm'])
print(s1)
print(type(s1))

0    28
1    20
2    32
3    40
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
# Dataframe
df = pd.DataFrame({'age':s1,'name':s2})
print(df)
print(type(df))

   age   name
0   28   John
1   20  David
2   32   Reva
3   40  Grahm
<class 'pandas.core.frame.DataFrame'>

In [ ]:
# Different Ways of creating a dataframe
# List of list
list_of_lists = [['John', 20,'NY'], ['David', 20, 'CL'], ['Reva', 32],['Grahm',40,'NZ']]
df = pd.DataFrame(list_of_lists, columns = ['name','age','city'])
print(df)

    name  age  city
0   John   20    NY
1  David   20    CL
2   Reva   32  None
3  Grahm   40    NZ

In [ ]:
# Use Dictionaries --> Most Common way to create dataframe
name_dict = {'name':['John','David','Reva','Grahm'], 'age':[28, 20, 32, 40]}
# Name of column as key and value as records for that specific column
# Create DataFrame
df = pd.DataFrame(name_dict)
print(df)

    name  age
0   John   28
1  David   20
2   Reva   32
3  Grahm   40

In [ ]:
# list of dictionaries
list_dict = [{'name':'John','age':28,'city':'NY'},{'name':'David','age':20,'city':'CA'},{'name':'Reva','age':32,'city':'AUS'},{'name':'Grahm','age':40,'city':'NZ'}]

# Create DataFrame
df = pd.DataFrame(list_dict)
print(df)

    name  age city
0   John   28   NY
1  David   20   CA
2   Reva   32  AUS
3  Grahm   40   NZ

### Setting up the directory

In [ ]:
# Project data files - https://drive.google.com/drive/folders/1vLMCY81mZ2l_zNRsiK2Trs1DtumITSla?usp=sharing

In [ ]:
import os
os.getcwd() # Get the current directory

'/content/sample_data'

In [ ]:
!ls # Command to see the folder available

anscombe.json		     california_housing_train.csv  mnist_test.csv	  README.md
california_housing_test.csv  dataframe.xlsx		   mnist_train_small.csv

In [ ]:
# Setting up directory helps access the files easily.
os.chdir('/content/sample_data')
os.getcwd()

'/content/sample_data'

In [ ]:
# Example of loading the file
# df = pd.read_csv('mnist_test.csv')

In [ ]:
# df.head(1)

In [ ]:
# Note: Google colab can't access the files or folder present in the google drive unless it it mounted

In [ ]:
# Mounting the drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
os.getcwd()

'/content/sample_data'

In [ ]:
# Change the working directory to project folder
os.chdir('/content/drive/MyDrive/M2_Project')
os.getcwd()

'/content/drive/MyDrive/M2_Project'

In [ ]:
!ls # List the files

bash.xml  employee.json  Products.xlsx	       read_imdb_data_w.xlsx
cache	  imdb_data.csv  read_imdb_data_w.csv  Superstore.xlsx

In [ ]:
os.getcwd()

'/content/drive/MyDrive/M2_Project'

In [ ]:
# os.chdir()

In [ ]:
# pd.read_csv('/content/drive/MyDrive/A0Z5AGRAGTQK (1).csv')

### Loading different file formats

#### Different types of file
1. CSV
2. Excel
3. JSON (JavaScript Object Notation)
4. XML (Extensible Markup Language)

In [ ]:
!ls

sample_data

In [ ]:
# Reading CSV file
read_imdb_data = pd.read_csv('imdb_data.csv')
read_imdb_data.head(1)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651

In [ ]:
!ls

In [ ]:
# Read Excel file
# Default first sheet
df = pd.read_excel("Products.xlsx")
print(df)

# Mention Sheet name
df = pd.read_excel("Products.xlsx",sheet_name = 'grocery')
print(df)

In [ ]:
# JSON (JavaScript Object Notation)
df = pd.read_json('employee.json')
df

In [ ]:
# Reading XML File
df = pd.read_xml('bash.xml')
df

### Basic Inspection of dataset

In [ ]:
# shape,head(n),tail(n),columns,describe(),info()

In [ ]:
read_imdb_data.shape

(3000, 23)

In [ ]:
read_imdb_data.head(1) # First n rows : default 5

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651

In [ ]:
read_imdb_data.tail(1) # last n rows : default 5

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

In [ ]:
read_imdb_data.columns # name of columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [ ]:
read_imdb_data.describe() # Inspection of continous data

                id        budget   popularity      runtime       revenue
count  3000.000000  3.000000e+03  3000.000000  2998.000000  3.000000e+03
mean   1500.500000  2.253133e+07     8.463274   107.856571  6.672585e+07
std     866.169729  3.702609e+07    12.104000    22.086434  1.375323e+08
min       1.000000  0.000000e+00     0.000001     0.000000  1.000000e+00
25%     750.750000  0.000000e+00     4.018053    94.000000  2.379808e+06
50%    1500.500000  8.000000e+06     7.374861   104.000000  1.680707e+07
75%    2250.250000  2.900000e+07    10.890983   118.000000  6.891920e+07
max    3000.000000  3.800000e+08   294.337037   338.000000  1.519558e+09

In [ ]:
read_imdb_data.describe(include= 'all') # Analysis of continous & Categorical data

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
count,3000.000000,604,3.000000e+03,2993,946,3000,3000,3000,2992,3000.000000,...,3000,2998.000000,2980,3000,2403,3000,2724,2987,2984,3.000000e+03
unique,NaN,422,NaN,872,941,3000,36,2975,2992,NaN,...,2398,NaN,401,2,2400,2969,2648,2975,2984,NaN
top,NaN,"[{'id': 645, 'name': 'James Bond Collection', ...",NaN,"[{'id': 18, 'name': 'Drama'}]",http://www.transformersmovie.com/,tt2637294,en,Joshua,"When Lou, who has become the ""father of the In...",NaN,...,9/10/10,NaN,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Based on a true story.,The Magnificent Seven,"[{'id': 10183, 'name': 'independent film'}]",[],"[{'credit_id': '59ac067c92514107af02c8c8', 'de...",NaN
freq,NaN,16,NaN,266,4,1,2575,2,1,NaN,...,5,NaN,1817,2996,3,2,27,13,1,NaN
mean,1500.500000,NaN,2.253133e+07,NaN,NaN,NaN,NaN,NaN,NaN,8.463274,...,NaN,107.856571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.672585e+07
std,866.169729,NaN,3.702609e+07,NaN,NaN,NaN,NaN,NaN,NaN,12.104000,...,NaN,22.086434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.375323e+08
min,1.000000,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,0.000001,...,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+00
25%,750.750000,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,4.018053,...,NaN,94.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.379808e+06
50%,1500.500000,NaN,8.000000e+06,NaN,NaN,NaN,NaN,NaN,NaN,7.374861,...,NaN,104.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.680707e+07
75%,2250.250000,NaN,2.900000e+07,NaN,NaN,NaN,NaN,NaN,NaN,10.890983,...,NaN,118.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.891920e+07
max,3000.000000,NaN,3.800000e+08,NaN,NaN,NaN,NaN,NaN,NaN,294.337037,...,NaN,338.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.519558e+09

In [ ]:
read_imdb_data.info() # Information about dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   object
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
dtypes: float64(2), int64(3), object(18)
memory usage: 539.2+ KB

In [ ]:
# Inspection of select few columns
read_imdb_data[['id', 'original_title','runtime','revenue', 'budget', 'genres','imdb_id', 'original_language' ]]

,id,original_title,runtime,revenue,budget,genres,imdb_id,original_language
0,1,Hot Tub Time Machine 2,93.0,12314651,14000000,"[{'id': 35, 'name': 'Comedy'}]",tt2637294,en
1,2,The Princess Diaries 2: Royal Engagement,113.0,95149435,40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",tt0368933,en
2,3,Whiplash,105.0,13092000,3300000,"[{'id': 18, 'name': 'Drama'}]",tt2582802,en
3,4,Kahaani,122.0,16000000,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",tt1821480,hi
4,5,마린보이,118.0,3923970,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",tt1380152,ko
...,...,...,...,...,...,...,...,...
2995,2996,Chasers,102.0,1596687,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",tt0109403,en
2996,2997,Vi är bäst!,102.0,180590,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",tt2364975,sv
2997,2998,The Long Kiss Goodnight,120.0,89456761,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",tt0116908,en
2998,2999,Along Came Polly,90.0,171963386,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",tt0343135,en
2999,3000,Abduction,106.0,82087155,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",tt1600195,en

In [ ]:
# Important Points to remember :

### Indexing and Slicing()

In [ ]:
# loc(), iloc(), Boolean indexing

In [ ]:
# Understanding the index
# list of dictionaries
list_dict = [{'name':'John','age':28},{'name':'David','age':20},{'name':'Reva','age':32},{'name':'Grahm','age':40}]

# Create DataFrame
df = pd.DataFrame(list_dict,index = ['A','B','C','D'])
df

    name  age
A   John   28
B  David   20
C   Reva   32
D  Grahm   40

In [ ]:
df.loc[['A','C'],['name','age']] # 1st part row subset, 2nd part column

   name  age
A  John   28
C  Reva   32

In [ ]:
df.columns

Index(['name', 'age'], dtype='object')

In [ ]:
df

    name  age
A   John   28
B  David   20
C   Reva   32
D  Grahm   40

In [ ]:
df

    name  age
A   John   28
B  David   20
C   Reva   32
D  Grahm   40

In [ ]:
df.iloc[[1,3],[0]] # Column until 2nd index

    name
B  David
D  Grahm

In [ ]:
# loc(): When Subsetting is done by index and column names
# iloc(): When Subsetting is done by index and column number

# df.loc[10:40, ['name']]
# df.iloc[:4,:1]

In [ ]:
# .loc[] --> Column names defined and you want to deal few column
# .iloc[] -->

In [ ]:
# loc(): When Subsetting is done by index and column name
read_imdb_data.loc[50:55,['budget','genres','runtime']] # rows and columns

      budget                                             genres  runtime
50    560000  [{'id': 10749, 'name': 'Romance'}, {'id': 18, ...    102.0
51  12000000  [{'id': 12, 'name': 'Adventure'}, {'id': 35, '...    160.0
52         0  [{'id': 12, 'name': 'Adventure'}, {'id': 10751...     97.0
53         0  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...     98.0
54  20000000                     [{'id': 28, 'name': 'Action'}]    107.0
55         0  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...     95.0

In [ ]:
read_imdb_data.loc[:5,]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,8/6/87,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638

In [ ]:
read_imdb_data.loc[3:5,] # till 5 all columns, 3 & 5 is included

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,8/6/87,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638

In [ ]:
df

    name  age
A   John   28
B  David   20
C   Reva   32
D  Grahm   40

In [ ]:
df.index[-3:-1]

Index(['B', 'C'], dtype='object')

In [ ]:
df.loc[df.index[-3:-1],['name']]

    name
B  David
C   Reva

In [ ]:
read_imdb_data.index[-5:]

RangeIndex(start=2995, stop=3000, step=1)

In [ ]:
read_imdb_data.loc[read_imdb_data.index[-5:] , ] # last 5 data using loc :; Use .index to use the negative index

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,3/28/13,102.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,NaN,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

In [ ]:
# -50 to -40 rows using loc for read_imdb_data
# read_imdb_data.loc[read_imdb_data.index[-50:-40] , 'genres' ]

In [ ]:
read_imdb_data.loc[[34,56,78] , :] # Only specific rows

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
34,35,"[{'id': 90863, 'name': 'Rush Hour Collection',...",140000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0293564,en,Rush Hour 3,After an attempted assassination on Ambassador...,9.718111,...,8/8/07,91.0,"[{'iso_639_1': 'la', 'name': 'Latin'}, {'iso_6...",Released,The Rush Is On!,Rush Hour 3,"[{'id': 1704, 'name': 'ambassador'}]","[{'cast_id': 2, 'character': 'Det. James Carte...","[{'credit_id': '52fe43fac3a36847f807b5bd', 'de...",258022233
56,57,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.joueuse-lefilm.com/,tt1082009,fr,Joueuse,"In a small Corsican village, the life of Hélèn...",2.947980,...,8/5/09,97.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Queen to Play,"[{'id': 316, 'name': 'chess'}, {'id': 3797, 'n...","[{'cast_id': 1, 'character': 'H√©l√®ne', 'cred...","[{'credit_id': '52fe4624c3a36847f80eefcf', 'de...",1056938
78,79,NaN,0,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,tt0083064,en,Sharky's Machine,"Sharky gets busted back to working vice, where...",2.633399,...,12/18/81,122.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"If you mess with a cop like Sharky, you better...",Sharky's Machine,"[{'id': 108, 'name': 'transvestism'}, {'id': 6...","[{'cast_id': 3, 'character': 'Tom Sharky', 'cr...","[{'credit_id': '555507869251411e620004c9', 'de...",35610100

In [ ]:
read_imdb_data.loc[read_imdb_data.index[[-3,-1,-2]] , :] # Only specific rows if negative index is used.

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386

In [ ]:
read_imdb_data.loc[:10,]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,8/6/87,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638
6,7,NaN,14000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://www.thepossessionmovie.com/,tt0431021,en,The Possession,A young girl buys an antique box at a yard sal...,7.286477,...,8/30/12,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fear The Demon That Doesn't Fear God,The Possession,NaN,"[{'cast_id': 23, 'character': 'Clyde', 'credit...","[{'credit_id': '52fe4981c3a368484e12ee29', 'de...",85446075
7,8,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,tt0391024,en,Control Room,A chronicle which provides a rare window into ...,1.949044,...,1/15/04,84.0,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",Released,Different channels. Different truths.,Control Room,"[{'id': 917, 'name': 'journalism'}, {'id': 163...","[{'cast_id': 2, 'character': 'Himself', 'credi...","[{'credit_id': '52fe47a69251416c750a0daf', 'de...",2586511
8,9,"[{'id': 256377, 'name': 'The Muppet Collection...",0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0117110,en,Muppet Treasure Island,After telling the story of Flint's last journe...,6.902423,...,2/16/96,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Set sail for Muppet mayhem!,Muppet Treasure Island,"[{'id': 2041, 'name': 'island'}, {'id': 4418, ...","[{'cast_id': 1, 'character': 'Long John Silver...","[{'credit_id': '52fe43c89251416c7501deb3', 'de...",34327391
9,10,NaN,6000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...",NaN,tt0310281,en,A Mighty Wind,"In ""A Mighty Wind"", director Christopher Guest...",4.672036,...,4/16/03,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Back together for the first time, again.",A Mighty Wind,"[{'id': 11800, 'name': 'mockumentary'}, {'id':...","[{'cast_id': 24, 'character': 'Jonathan Steinb...","[{'credit_id': '52fe45609251416c750545b3', 'de...",18750246
10,11,"[{'id': 1575, 'name': 'Rocky Collection', 'pos...",1000000,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0075148,en,Rocky,"When world heavyweight boxing champion, Apollo...",14.774066,...,11/21/76,119.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,His whole life was a million-to-one shot.,Rocky,"[{'id': 240, 'name': 'underdog'}, {'id': 276, ...","[{'cast_id': 16, 'character': 'Rocky Balboa', ...","[{'credit_id': '579948e9c3a36874e9007b0b', 'de...",117235147

In [ ]:
# iloc : When Subsetting is done by row and column number
read_imdb_data.iloc[ : 10,  : 4] # index 10 & 4 is excluded

,id,belongs_to_collection,budget,genres
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]"
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam..."
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]"
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n..."
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam..."
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '..."
6,7,NaN,14000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam..."
7,8,NaN,0,"[{'id': 99, 'name': 'Documentary'}]"
8,9,"[{'id': 256377, 'name': 'The Muppet Collection...",0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam..."
9,10,NaN,6000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, '..."

In [ ]:
read_imdb_data.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [ ]:
read_imdb_data.iloc[ 3: 5,  1: 4] # index 5 & 4 is excluded

,belongs_to_collection,budget,genres
3,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n..."
4,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam..."

In [ ]:
read_imdb_data.loc[ read_imdb_data.index[-50:-40],  ]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
2950,2951,"[{'id': 9735, 'name': 'Friday the 13th Collect...",30000000,"[{'id': 27, 'name': 'Horror'}]",NaN,tt0329101,en,Freddy vs. Jason,Evil dream-demon Freddy Krueger devises a plan...,14.015739,...,8/15/03,97.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Evil Will Battle Evil,Freddy vs. Jason,"[{'id': 9826, 'name': 'murder'}, {'id': 10776,...","[{'cast_id': 1, 'character': 'Freddy Krueger',...","[{'credit_id': '52fe4453c3a36847f808f4a5', 'de...",114908830
2951,2952,NaN,13000000,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",NaN,tt2057392,en,Eye in the Sky,A military officer in command of a drone opera...,10.564701,...,9/11/15,102.0,"[{'iso_639_1': 'so', 'name': 'Somali'}, {'iso_...",Released,Welcome to the new front line,Eye in the Sky,"[{'id': 949, 'name': 'terrorist'}, {'id': 1193...","[{'cast_id': 4, 'character': 'Colonel Katherin...","[{'credit_id': '55186708c3a36862f6004623', 'de...",18704595
2952,2953,NaN,25000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",http://theageofadalinemovie.com,tt1655441,en,The Age of Adaline,After 29-year-old Adaline recovers from a near...,10.542026,...,4/16/15,112.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Love is timeless.,The Age of Adaline,"[{'id': 582, 'name': 'san francisco'}, {'id': ...","[{'cast_id': 0, 'character': 'Adaline Bowman',...","[{'credit_id': '54721093c3a3686792002bc5', 'de...",65663276
2953,2954,NaN,8500000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,tt0202677,en,The Way of the Gun,Parker and Longbaugh are a pair of low-level p...,6.036330,...,9/8/00,119.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,The Way of the Gun,"[{'id': 75, 'name': 'gunslinger'}, {'id': 534,...","[{'cast_id': 1, 'character': 'Mr. Longbaugh', ...","[{'credit_id': '52fe4305c3a36847f8034691', 'de...",19125401
2954,2955,NaN,60000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt0375173,en,Alfie,"In Manhattan, the British limousine driver Alf...",10.411608,...,10/22/04,103.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Meet a man who never met a woman he didn't love.,Alfie,"[{'id': 242, 'name': 'new york'}, {'id': 1332,...","[{'cast_id': 1, 'character': 'Alfie', 'credit_...","[{'credit_id': '562643e89251413ded006a07', 'de...",13395939
2955,2956,NaN,17000000,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,tt1210042,en,Brooklyn's Finest,Enforcing the law within the notoriously rough...,12.504220,...,1/16/09,133.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,This is War. This is Brooklyn.,Brooklyn's Finest,"[{'id': 255, 'name': 'male nudity'}, {'id': 29...","[{'cast_id': 3, 'character': 'Eddie Dugan', 'c...","[{'credit_id': '52fe4500c3a368484e042e7b', 'de...",29536299
2956,2957,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,tt0091055,en,Firewalker,A pair of adventurers try to track down an anc...,3.150899,...,11/21/86,104.0,"[{'iso_639_1': 'hu', 'name': 'Magyar'}, {'iso_...",Released,A pair of down-and-out fortune hunters cash in...,Firewalker,"[{'id': 352, 'name': 'secret passage'}, {'id':...","[{'cast_id': 1, 'character': 'Max Donigan', 'c...","[{'credit_id': '52fe45199251416c7504bbf7', 'de...",11949484
2957,2958,NaN,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0113845,en,Money Train,A vengeful New York transit cop decides to ste...,7.337906,...,11/21/95,103.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Get on, or GET OUT THE WAY!",Money Train,"[{'id': 380, 'name': 'brother brother relation...","[{'cast_id': 1, 'character': 'John', 'credit_i...","[{'credit_id': '52fe44509251416c750305a1', 'de...",35431113
2958,2959,NaN,15000000,"[{'id': 10402, 'name': 'Music'}, {'id': 99, 'n...",http://www.u23dmovie.com/,tt0892375,en,U2 3D,"A 3-D presentation of U2's global ""Vertigo"" to...",0.900864,...,5/19/07,85.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Hear See Experience,U2 3D,NaN,"[{'cast_id': 0, 'character': 'Himself', 'credi...","[{'credit_id': '57bfd2089251414b1500001e', 'de...",22730842
2959,2960,NaN,2300000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,tt1093370,hi,Jab We Met,"Depressed after the passing of his father, Dha...",3.959411,...,10/26/07,145.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,NaN,Jab We Met,"[{'id': 2038, 'name': ""love of one's life""}, {...","[{'cast_id': 9, 'character': 'Aditya Kashyap',...","[{'credit_id': '537ef0d8c3a36805a1002844', 'de...",4600000

In [ ]:
read_imdb_data.iloc[ -50:-40,  ] # last three rows and last 2 columns # No need to use .index here.

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
2950,2951,"[{'id': 9735, 'name': 'Friday the 13th Collect...",30000000,"[{'id': 27, 'name': 'Horror'}]",NaN,tt0329101,en,Freddy vs. Jason,Evil dream-demon Freddy Krueger devises a plan...,14.015739,...,8/15/03,97.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Evil Will Battle Evil,Freddy vs. Jason,"[{'id': 9826, 'name': 'murder'}, {'id': 10776,...","[{'cast_id': 1, 'character': 'Freddy Krueger',...","[{'credit_id': '52fe4453c3a36847f808f4a5', 'de...",114908830
2951,2952,NaN,13000000,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",NaN,tt2057392,en,Eye in the Sky,A military officer in command of a drone opera...,10.564701,...,9/11/15,102.0,"[{'iso_639_1': 'so', 'name': 'Somali'}, {'iso_...",Released,Welcome to the new front line,Eye in the Sky,"[{'id': 949, 'name': 'terrorist'}, {'id': 1193...","[{'cast_id': 4, 'character': 'Colonel Katherin...","[{'credit_id': '55186708c3a36862f6004623', 'de...",18704595
2952,2953,NaN,25000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",http://theageofadalinemovie.com,tt1655441,en,The Age of Adaline,After 29-year-old Adaline recovers from a near...,10.542026,...,4/16/15,112.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Love is timeless.,The Age of Adaline,"[{'id': 582, 'name': 'san francisco'}, {'id': ...","[{'cast_id': 0, 'character': 'Adaline Bowman',...","[{'credit_id': '54721093c3a3686792002bc5', 'de...",65663276
2953,2954,NaN,8500000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,tt0202677,en,The Way of the Gun,Parker and Longbaugh are a pair of low-level p...,6.036330,...,9/8/00,119.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,The Way of the Gun,"[{'id': 75, 'name': 'gunslinger'}, {'id': 534,...","[{'cast_id': 1, 'character': 'Mr. Longbaugh', ...","[{'credit_id': '52fe4305c3a36847f8034691', 'de...",19125401
2954,2955,NaN,60000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt0375173,en,Alfie,"In Manhattan, the British limousine driver Alf...",10.411608,...,10/22/04,103.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Meet a man who never met a woman he didn't love.,Alfie,"[{'id': 242, 'name': 'new york'}, {'id': 1332,...","[{'cast_id': 1, 'character': 'Alfie', 'credit_...","[{'credit_id': '562643e89251413ded006a07', 'de...",13395939
2955,2956,NaN,17000000,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,tt1210042,en,Brooklyn's Finest,Enforcing the law within the notoriously rough...,12.504220,...,1/16/09,133.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,This is War. This is Brooklyn.,Brooklyn's Finest,"[{'id': 255, 'name': 'male nudity'}, {'id': 29...","[{'cast_id': 3, 'character': 'Eddie Dugan', 'c...","[{'credit_id': '52fe4500c3a368484e042e7b', 'de...",29536299
2956,2957,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,tt0091055,en,Firewalker,A pair of adventurers try to track down an anc...,3.150899,...,11/21/86,104.0,"[{'iso_639_1': 'hu', 'name': 'Magyar'}, {'iso_...",Released,A pair of down-and-out fortune hunters cash in...,Firewalker,"[{'id': 352, 'name': 'secret passage'}, {'id':...","[{'cast_id': 1, 'character': 'Max Donigan', 'c...","[{'credit_id': '52fe45199251416c7504bbf7', 'de...",11949484
2957,2958,NaN,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0113845,en,Money Train,A vengeful New York transit cop decides to ste...,7.337906,...,11/21/95,103.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Get on, or GET OUT THE WAY!",Money Train,"[{'id': 380, 'name': 'brother brother relation...","[{'cast_id': 1, 'character': 'John', 'credit_i...","[{'credit_id': '52fe44509251416c750305a1', 'de...",35431113
2958,2959,NaN,15000000,"[{'id': 10402, 'name': 'Music'}, {'id': 99, 'n...",http://www.u23dmovie.com/,tt0892375,en,U2 3D,"A 3-D presentation of U2's global ""Vertigo"" to...",0.900864,...,5/19/07,85.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Hear See Experience,U2 3D,NaN,"[{'cast_id': 0, 'character': 'Himself', 'credi...","[{'credit_id': '57bfd2089251414b1500001e', 'de...",22730842
2959,2960,NaN,2300000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,tt1093370,hi,Jab We Met,"Depressed after the passing of his father, Dha...",3.959411,...,10/26/07,145.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,NaN,Jab We Met,"[{'id': 2038, 'name': ""love of one's life""}, {...","[{'cast_id': 9, 'character': 'Aditya Kashyap',...","[{'credit_id': '537ef0d8c3a36805a1002844', 'de...",4600000

In [ ]:
read_imdb_data.iloc[ [3,6,9],  [3,6,7] ] # Custom Indexes

,genres,original_language,original_title
3,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",hi,Kahaani
6,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",en,The Possession
9,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...",en,A Mighty Wind

In [ ]:
# [True,True]+[False]*2998 # 3000 rows

In [ ]:
read_imdb_data.shape

(3000, 23)

In [ ]:
## Boolean Index
# Use of conditional and logical operator
list_boolean = [True,False,True]+[False]*2997
read_imdb_data.loc[list_boolean,] # Understand this interesting concept

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000

In [ ]:
read_imdb_data.head(5)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970

In [ ]:
df

    name  age
A   John   28
B  David   20
C   Reva   32
D  Grahm   40

In [ ]:
df.loc[ [True,False, False, True] , ]

    name  age
A   John   28
D  Grahm   40

In [ ]:
df.iloc[ [True,False,True,True] , ]

    name  age
A   John   28
C   Reva   32
D  Grahm   40

In [ ]:
filter_boolean = read_imdb_data.loc[:,['runtime']] > 120
print(filter_boolean)

      runtime
0       False
1       False
2       False
3        True
4       False
...       ...
2995    False
2996    False
2997    False
2998    False
2999    False

[3000 rows x 1 columns]

In [ ]:
filter_boolean['runtime']

0       False
1       False
2       False
3        True
4       False
        ...
2995    False
2996    False
2997    False
2998    False
2999    False
Name: runtime, Length: 3000, dtype: bool

In [ ]:
filter_boolean = read_imdb_data.loc[:,['runtime']] > 120
read_imdb_data_120plus = read_imdb_data.loc[filter_boolean['runtime'],] # Conditional Subsetting

In [ ]:
# read_imdb_data_120plus.head()

In [ ]:
# ~[True, False, True] --> [False, True, False]

In [ ]:
read_imdb_data.loc[~filter_boolean['runtime'],] # Reverse Conditional Subsetting

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,8/6/87,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,3/28/13,102.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,NaN,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

In [ ]:
# Multiple conditions
condition1 = read_imdb_data.loc[:,['runtime']] > 120
condition2 = read_imdb_data.loc[:,['original_language']] =='en'
# read_imdb_data.loc[condition1['runtime'] & condition2['original_language'],] # and condition - Note : here & is used not 'and'
read_imdb_data.loc[condition1['runtime'] | condition2['original_language'],] # or condition - Note : here | is used not 'or'

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,8/6/87,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2994,2995,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0105327,en,School Ties,When David Greene receives a football scholars...,7.438381,...,9/18/92,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just because you’re accepted doesn’t mean you ...,School Ties,"[{'id': 6075, 'name': 'sport'}, {'id': 10144, ...","[{'cast_id': 2, 'character': 'David Greene', '...","[{'credit_id': '5637777ac3a3681b4d01f9f5', 'de...",14715067
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

In [ ]:
# Important Points to remember :
# iloc vs loc
# --> loc : Index& columns names , iloc : Index number and Column number is considered
# --> loc : Range (a:b) , b is included, iloc:Range (a:b) , b is excluded

### Creating new columns, renaming & droping

#### Rename

In [ ]:
# dataframe.rename(columns={'column_name':'new_column_name'},inplace=True) # Syntax

In [ ]:
read_imdb_data.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [ ]:
# read_imdb_data.rename(columns = {'budget':'movie_budget','cast':'movie_cast'})
read_imdb_data.rename(columns = {'budget':'movie_budget','cast':'movie_cast'}, inplace= True)

In [ ]:
read_imdb_data.head(1)

,id,belongs_to_collection,movie_budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,movie_cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651

#### New Columns

In [ ]:
# read_imdb_data['runtime'] #-- This feature is going to be removed

In [ ]:
read_imdb_data.loc[:,'half_runtime'] = read_imdb_data.loc[:, 'runtime'] * 0.5
read_imdb_data

,id,belongs_to_collection,movie_budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,Keywords,movie_cast,crew,revenue,half_runtime
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,56.5
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,52.5
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687,51.0
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,102.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,NaN,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590,51.0
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761,60.0
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386,45.0
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155,53.0

In [ ]:
read_imdb_data.loc[:,'revenue_runtime_ratio'] = (read_imdb_data.loc[:, 'revenue'] / read_imdb_data.loc[:, 'runtime'])
read_imdb_data

,id,belongs_to_collection,movie_budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,movie_cast,crew,revenue,half_runtime,revenue_runtime_ratio
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5,1.324156e+05
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,56.5,8.420304e+05
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,52.5,1.246857e+05
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0,1.311475e+05
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0,3.325398e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687,51.0,1.565379e+04
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,NaN,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590,51.0,1.770490e+03
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761,60.0,7.454730e+05
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386,45.0,1.910704e+06
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155,53.0,7.744071e+05

In [ ]:
read_imdb_data['check'] = list(range(1,3001))

In [ ]:
# len(list(range(1,3001)))

In [ ]:
read_imdb_data.head()

,id,belongs_to_collection,movie_budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,status,tagline,title,Keywords,movie_cast,crew,revenue,half_runtime,revenue_runtime_ratio,check
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5,132415.602151,1
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,56.5,842030.398230,2
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,52.5,124685.714286,3
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0,131147.540984,4
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0,33253.983051,5

#### Drop columns & rows

In [ ]:
read_imdb_data.drop(['check'],axis = 1, inplace = True) # Drop column
read_imdb_data.head(1)

,id,belongs_to_collection,movie_budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,movie_cast,crew,revenue,half_runtime,revenue_runtime_ratio
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5,132415.602151

In [ ]:
read_imdb_data.drop([0,1,2], axis = 0) # Drop rows

,id,belongs_to_collection,movie_budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,movie_cast,crew,revenue,half_runtime,revenue_runtime_ratio
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0,1.311475e+05
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0,3.325398e+04
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638,41.5,3.929684e+04
6,7,NaN,14000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://www.thepossessionmovie.com/,tt0431021,en,The Possession,A young girl buys an antique box at a yard sal...,7.286477,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fear The Demon That Doesn't Fear God,The Possession,NaN,"[{'cast_id': 23, 'character': 'Clyde', 'credit...","[{'credit_id': '52fe4981c3a368484e12ee29', 'de...",85446075,46.0,9.287617e+05
7,8,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,tt0391024,en,Control Room,A chronicle which provides a rare window into ...,1.949044,...,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",Released,Different channels. Different truths.,Control Room,"[{'id': 917, 'name': 'journalism'}, {'id': 163...","[{'cast_id': 2, 'character': 'Himself', 'credi...","[{'credit_id': '52fe47a69251416c750a0daf', 'de...",2586511,42.0,3.079180e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687,51.0,1.565379e+04
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,NaN,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590,51.0,1.770490e+03
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761,60.0,7.454730e+05
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386,45.0,1.910704e+06
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155,53.0,7.744071e+05

In [ ]:
# .drop : names of index or column, axis default is 0

### Handling Missing Values

In [ ]:
read_imdb_data.head(1)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651

In [ ]:
# Identify, Drop or fill
# isna(),dropna(), fillna()

In [ ]:
3000-604

2396

In [ ]:
read_imdb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   object
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
dtypes: float64(2), int64(3), object(18)
memory usage: 539.2+ KB

In [ ]:
read_imdb_data.loc[:,'belongs_to_collection'].head(10)

0    [{'id': 313576, 'name': 'Hot Tub Time Machine ...
1    [{'id': 107674, 'name': 'The Princess Diaries ...
2                                                  NaN
3                                                  NaN
4                                                  NaN
5                                                  NaN
6                                                  NaN
7                                                  NaN
8    [{'id': 256377, 'name': 'The Muppet Collection...
9                                                  NaN
Name: belongs_to_collection, dtype: object

In [ ]:
sum(read_imdb_data.loc[:,'belongs_to_collection'].isna())/read_imdb_data.shape[0]

0.7986666666666666

In [ ]:
read_imdb_data.loc[:,'belongs_to_collection'].isna()

0       False
1       False
2        True
3        True
4        True
        ...
2995     True
2996     True
2997     True
2998     True
2999     True
Name: belongs_to_collection, Length: 3000, dtype: bool

In [ ]:
read_imdb_data.belongs_to_collection.isna() #Method 1

0       False
1       False
2        True
3        True
4        True
        ...
2995     True
2996     True
2997     True
2998     True
2999     True
Name: belongs_to_collection, Length: 3000, dtype: bool

In [ ]:
read_imdb_data['belongs_to_collection'].isna() # Method 2

0       False
1       False
2        True
3        True
4        True
        ...
2995     True
2996     True
2997     True
2998     True
2999     True
Name: belongs_to_collection, Length: 3000, dtype: bool

In [ ]:
read_imdb_data.loc[:,'belongs_to_collection'].isna()

0       False
1       False
2        True
3        True
4        True
        ...
2995     True
2996     True
2997     True
2998     True
2999     True
Name: belongs_to_collection, Length: 3000, dtype: bool

In [ ]:
# Identify - subset the data as per the null values
read_imdb_data.loc[read_imdb_data.belongs_to_collection.isna(),].head(2)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000

In [ ]:
read_imdb_data.dropna() # Remove all rows having Na anywhere

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
22,23,"[{'id': 207621, 'name': 'V/H/S Collection', 'p...",0,"[{'id': 53, 'name': 'Thriller'}, {'id': 27, 'n...",http://www.magnetreleasing.com/vhs/,tt2105044,en,V/H/S,When a group of misfits is hired by an unknown...,7.820787,...,7/28/12,116.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,This collection is killer.,V/H/S,"[{'id': 6435, 'name': 'webcam'}, {'id': 9706, ...","[{'cast_id': 1, 'character': 'Gary', 'credit_i...","[{'credit_id': '52fe48ee9251416c9109d113', 'de...",100345
40,41,"[{'id': 376970, 'name': 'Cocaine Cowboys', 'po...",0,"[{'id': 28, 'name': 'Action'}, {'id': 99, 'nam...",http://www.magpictures.com/profile.aspx?id=983...,tt0380268,en,Cocaine Cowboys,"In the 1980s, ruthless Colombian cocaine baron...",2.941626,...,4/26/06,118.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,How Miami became the cocaine capital of the Un...,Cocaine Cowboys,"[{'id': 2150, 'name': 'cocaine'}, {'id': 2231,...","[{'cast_id': 2, 'character': 'Himself', 'credi...","[{'credit_id': '52fe46179251416c7506cc15', 'de...",163000
46,47,"[{'id': 8354, 'name': 'Ice Age Collection', 'p...",80000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",http://www.iceagemovies.com/films/ice-age-the-...,tt0438097,en,Ice Age: The Meltdown,"Diego, Manny and Sid return in this sequel to ...",16.646029,...,3/23/06,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Ice age is melting away.,Ice Age: The Meltdown,"[{'id': 2078, 'name': 'mammoth'}, {'id': 2079,...","[{'cast_id': 1, 'character': 'Manny (voice)', ...","[{'credit_id': '52fe4292c3a36847f80292c9', 'de...",660940780
60,61,"[{'id': 645, 'name': 'James Bond Collection', ...",150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/#/our-titles/233/Casino-Roy...,tt0381061,en,Casino Royale,"Le Chiffre, a banker to the world's terrorists...",23.065078,...,11/14/06,144.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Everyone has a past. Every legend has a beginn...,Casino Royale,"[{'id': 131, 'name': 'italy'}, {'id': 383, 'na...","[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '53ac1fd7c3a3684bc8001908', 'de...",599045960
69,70,"[{'id': 9485, 'name': 'The Fast and the Furiou...",85000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",http://www.thefastandthefurious3.com/,tt0463985,en,The Fast and the Furious: Tokyo Drift,"In order to avoid a jail sentence, Sean Boswel...",2.238808,...,6/3/06,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"On the streets of Tokyo, speed needs no transl...",The Fast and the Furious: Tokyo Drift,"[{'id': 830, 'name': 'car race'}, {'id': 1926,...","[{'cast_id': 12, 'character': 'Sean Boswell', ...","[{'credit_id': '56784ed792514111900002c8', 'de...",158468292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2904,2905,"[{'id': 424202, 'name': 'Trainspotting Collect...",4000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://www.miramax.com/movie/trainspotting/,tt0117951,en,Trainspotting,"Renton, deeply immersed in the Edinburgh drug ...",19.348466,...,2/23/96,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Choose life.,Trainspotting,"[{'id': 212, 'name': 'london england'}, {'id':...","[{'cast_id': 17, 'character': 'Mark Renton', '...","[{'credit_id': '52fe4260c3a36847f80198c1', 'de...",16491080
2927,2928,"[{'id': 645, 'name': 'James Bond Collection', ...",140000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/view/movie/232/Die-Another-...,tt0246460,en,Die Another Day,Bond takes on a North Korean leader who underg...,12.996474,...,11/17/02,133.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,He’s never been cooler.,Die Another Day,"[{'id': 3290, 'name': 'laser'}, {'id': 156095,...","[{'cast_id': 20, 'character': 'James Bond', 'c...","[{'credit_id': '52fe45ff9251416c91045a7f', 'de...",431971116
2938,2939,"[{'id': 135416, 'name': 'Prometheus Collection...",130000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://www.projectprometheus.com/,tt1446714,en,Prometheus,A team of explorers discover a clue to the ori...,16.624854,...,5/30/12,124.0,"[{'iso_639_1': 'gd', 'name': ''}, {'iso_639_1'...",Released,The Search for Our Beginning Could Lead to Our...,Prometheus,"[{'id': 803, 'name': 'android'}, {'id': 4565, ...","[{'cast_id': 5, 'character': 'Dr. Elizabeth Sh...","[{'credit_id': '52fe481dc3a368484e0e9db7', 'de...",403170142
2968,2969,"[{'id': 97307, 'name': 'BloodRayne Collection'...",25000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.bloodrayne-themovie.com/main/index....,tt0383222,en,BloodRayne,"In eighteenth century Romania, Rayne, a dhampi...",6.514132,...,10/22/05,95.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Revenge never tasted so sweet.,BloodRayne,"[{'id': 3133, 'name': 'vampire'}, {'id': 9259,...","[{'cast_id': 3, 'character': 'Rayne', 'credit_...","[{'credit_id': '52fe4cd4c3a36847f82407f7', 'de...",2405420
2984,2985,"[{'id': 221111, 'name': 'S.W.A.T. Collection',...",80000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",http://www.sonypictures.com/homevideo/swat/,tt0257076,en,S.W.A.T.,Hondo Harrelson recruits Jim Street to join an...,13.334952,...,8/8/03,117.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,You're either S.W.A.T. or you're not.,S.W.A.T.,"[{'id': 2434, 'name': 'liberation'}, {'id': 35...","[{'cast_id': 25, 'character': ""Sgt. Dan 'Hondo...","[{'credit_id': '5379d4980e0a261431006f58', 'de...",116643346

In [ ]:
read_imdb_data.shape

(3000, 23)

In [ ]:
# read_imdb_data.loc[~read_imdb_data.loc[:,'belongs_to_collection'].isna(),]

In [ ]:
# fillna()
read_imdb_data_copy = read_imdb_data.copy()

In [ ]:
# Full data impute with some value
read_imdb_data_copy.fillna('Value not available')

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",Value not available,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Value not available,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,Value not available,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,Value not available,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Value not available,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,Value not available,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",Value not available,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,Value not available,Marine Boy,Value not available,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,Value not available,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",Value not available,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687
2996,2997,Value not available,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",Value not available,tt2364975,sv,Vi är bäst!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,3/28/13,102.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,Value not available,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590
2997,2998,Value not available,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",Value not available,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2998,2999,Value not available,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386
2999,3000,Value not available,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

In [ ]:
# Fillna on specific column
read_imdb_data_copy.belongs_to_collection = read_imdb_data_copy.belongs_to_collection.fillna(' Missing Value')

In [ ]:
read_imdb_data_copy.head(5)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,Missing Value,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,Missing Value,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,Missing Value,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970

In [ ]:
(60+62+98)/3

73.33333333333333

In [ ]:
# Fill the null value
# Categorical - 'Missing'/'Others'/Most frequent value
# Continous - mean / median

In [ ]:
# Visualisation --: Outlier

### Sorting & Handling Duplicates

In [ ]:
# Sorting : sort_values

In [ ]:
# Creating a DataFrame
data = {'A': [1, 3, 2, 1, 2],
        'B': ['a', 'b', 'c', 'a', 'b'],
        'C':[0, 1, 9, 0, 2]}
df = pd.DataFrame(data)
df

   A  B  C
0  1  a  0
1  3  b  1
2  2  c  9
3  1  a  0
4  2  b  2

In [ ]:
# Sorting by column A
df_sorted = df.sort_values(by='A') # default ascending

print(df_sorted)

   A  B  C
0  1  a  0
3  1  a  0
2  2  c  9
4  2  b  2
1  3  b  1

In [ ]:
# Sorting by column A -  Descending
df.sort_values(by='A', ascending = False)

   A  B  C
1  3  b  1
2  2  c  9
4  2  b  2
0  1  a  0
3  1  a  0

In [ ]:
# Sorting by column A & Column B
df.sort_values(by= ['A','B'], ascending = [False,False])

   A  B  C
1  3  b  1
2  2  c  9
4  2  b  2
0  1  a  0
3  1  a  0

In [ ]:
df.sort_values(by= ['A','B'], ascending = [False,True])

   A  B  C
1  3  b  1
4  2  b  2
2  2  c  9
0  1  a  0
3  1  a  0

In [ ]:
df.sort_values(by= ['B','A'], ascending = [False,True])

   A  B  C
2  2  c  9
4  2  b  2
1  3  b  1
0  1  a  0
3  1  a  0

In [ ]:
# Sorting by column A & Column B : A Ascending & B descending
df.sort_values(by=['A','B'], ascending = [True,False])

   A  B  C
0  1  a  0
3  1  a  0
2  2  c  9
4  2  b  2
1  3  b  1

In [ ]:
# Implement it on IMDB data
read_imdb_data.head(1)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651

In [ ]:
# read_imdb_data.sort_values(by = 'runtime',ascending  = False)

In [ ]:
df

   A  B  C
0  1  a  0
1  3  b  1
2  2  c  9
3  1  a  0
4  2  b  2

In [ ]:
# groupby([all columns])['id'].count()

In [ ]:
df.loc[:,['A','B']].value_counts().reset_index()

   A  B  count
0  1  a      2
1  2  b      1
2  2  c      1
3  3  b      1

In [ ]:
sum(df.value_counts().reset_index()['count']>1)

1

In [ ]:
## value_counts() : Count the value # and create the column count.
sum(df.value_counts().reset_index()['count']>1) # How many rows are there having duplicated values?

1

In [ ]:
# Convert it dataframe format
df.value_counts().reset_index()

   A  B  C  count
0  1  a  0      2
1  2  b  2      1
2  2  c  9      1
3  3  b  1      1

In [ ]:
read_imdb_data_dup = pd.concat([read_imdb_data,read_imdb_data.iloc[40:50,:]]) # Created the duplicate records

In [ ]:
read_imdb_data_dup.value_counts().reset_index().sort_values('count',ascending = False)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,count
0,41,"[{'id': 376970, 'name': 'Cocaine Cowboys', 'po...",0,"[{'id': 28, 'name': 'Action'}, {'id': 99, 'nam...",http://www.magpictures.com/profile.aspx?id=983...,tt0380268,en,Cocaine Cowboys,"In the 1980s, ruthless Colombian cocaine baron...",2.941626,...,118.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,How Miami became the cocaine capital of the Un...,Cocaine Cowboys,"[{'id': 2150, 'name': 'cocaine'}, {'id': 2231,...","[{'cast_id': 2, 'character': 'Himself', 'credi...","[{'credit_id': '52fe46179251416c7506cc15', 'de...",163000,2
1,47,"[{'id': 8354, 'name': 'Ice Age Collection', 'p...",80000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",http://www.iceagemovies.com/films/ice-age-the-...,tt0438097,en,Ice Age: The Meltdown,"Diego, Manny and Sid return in this sequel to ...",16.646029,...,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Ice age is melting away.,Ice Age: The Meltdown,"[{'id': 2078, 'name': 'mammoth'}, {'id': 2079,...","[{'cast_id': 1, 'character': 'Manny (voice)', ...","[{'credit_id': '52fe4292c3a36847f80292c9', 'de...",660940780,2
201,1116,"[{'id': 645, 'name': 'James Bond Collection', ...",14000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/view/movie/1891/The-Spy-Who...,tt0076752,en,The Spy Who Loved Me,Russian and British submarines with nuclear mi...,9.781451,...,125.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,It's the BIGGEST. It's the BEST. It's BOND. An...,The Spy Who Loved Me,"[{'id': 212, 'name': 'london england'}, {'id':...","[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '52fe426bc3a36847f801d187', 'de...",185438673,1
138,208,"[{'id': 286162, 'name': 'Power Rangers Collect...",15000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.powerrangers.com/,tt0113820,en,Mighty Morphin Power Rangers: The Movie,Power up with six incredible teens who out-man...,7.024227,...,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Power Is On!,Mighty Morphin Power Rangers: The Movie,"[{'id': 10988, 'name': 'based on tv series'}, ...","[{'cast_id': 2, 'character': 'Kimberly Hart / ...","[{'credit_id': '52fe44d8c3a36847f80ad707', 'de...",66000000,1
128,539,"[{'id': 84, 'name': 'Indiana Jones Collection'...",48000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.indianajones.com/crusade,tt0097576,en,Indiana Jones and the Last Crusade,When Dr. Henry Jones Sr. suddenly goes missing...,14.788987,...,127.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,"The man with the hat is back. And this time, h...",Indiana Jones and the Last Crusade,"[{'id': 83, 'name': 'saving the world'}, {'id'...","[{'cast_id': 8, 'character': 'Indiana Jones', ...","[{'credit_id': '52fe4216c3a36847f8002e69', 'de...",474171806,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2891,"[{'id': 14563, 'name': 'The Ring Collection', ...",25000000,"[{'id': 27, 'name': 'Horror'}]",http://www.ringsmovie.com/,tt0498381,en,Rings,"Julia becomes worried about her boyfriend, Hol...",24.535733,...,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Evil is reborn.,Rings,"[{'id': 3298, 'name': 'hallucination'}, {'id':...","[{'cast_id': 14, 'character': 'Julia', 'credit...","[{'credit_id': '52fe46019251416c75069e25', 'de...",83080890,1
71,2892,"[{'id': 479888, 'name': 'The Thing Collection'...",35000000,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...",http://www.uphe.com/movies/the-thing-2011,tt0905372,en,The Thing,When paleontologist Kate Lloyd travels to an i...,10.169411,...,103.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,It's Not Human. Yet.,The Thing,"[{'id': 2340, 'name': 'paranoia'}, {'id': 4713...","[{'cast_id': 2, 'character': 'Kate Lloyd', 'cr...","[{'credit_id': '537b713fc3a3682d3c00000e', 'de...",28128670,1
72,2905,"[{'id': 424202, 'name': 'Trainspotting Collect...",4000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://www.miramax.com/movie/trainspotting/,tt0117951,en,Trainspotting,"Renton, deeply immersed in the Edinburgh drug ...",19.348466,...,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Choose life.,Trainspotting,"[{'id': 212, 'name': 'london england'}, {'id':...","[{'cast_id': 17, 'character': 'Mark Renton', '...","[{'credit_id': '52fe4260c3a36847f80198c1', 'de...",16491080,1
73,2928,"[{'id': 645, 'name': 'James Bond Collection', ...",140000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/view/movie/232/Die-Another-...,tt0246460,en,Die Another Day,Bond takes on a North Korean leader who underg...,12.996474,...,133.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,He’s never been cooler.,Die Another Day,"[{'id': 3290, 'name': 'laser'}, {'id': 156095,...","[{'cast_id': 20, 'character': 'James Bond', 'c...","[{'credit_id': '52fe45ff9251416c91045a7f', 'de...",431971116,1
202,2985,"[{'id': 221111, 'name': 'S.W.A.T. Collection',...",80000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",http://www.sonypictures.com/homevideo/swat/,tt0257076,en,S.W.A.T.,Hondo Harrelson recruits Jim Street to join an...,13.334952,...,117.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,You're either S.W.A.T. or you're not.,S.W.A.T.,"[{'id': 2434, 'name': 'liberation'}, {'id': 35...","[{'cast_id': 25, 'character': ""Sgt. Dan 'Hondo...","[{'credit_id': '5379d4980e0a261431006f58', 'de...",116643346,1

In [ ]:
# Convert it dataframe format
df.value_counts().reset_index().sort_values('count')

   A  B  C  count
1  2  b  2      1
2  2  c  9      1
3  3  b  1      1
0  1  a  0      2

In [ ]:
df['B'].value_counts().reset_index()

   B  count
0  a      2
1  b      2
2  c      1

In [ ]:
df

   A  B  C
0  1  a  0
1  3  b  1
2  2  c  9
3  1  a  0
4  2  b  2

In [ ]:
# Drop duplicates
# .drop_duplicates() , subset & keep parameters
df.drop_duplicates() # Drop duplicates for the dataframe # Load the data in dataframe.

   A  B  C
0  1  a  0
1  3  b  1
2  2  c  9
4  2  b  2

In [ ]:
df.sort_values(by = 'A') # Column A as customer

   A  B  C
0  1  a  0
3  1  a  0
2  2  c  9
4  2  b  2
1  3  b  1

In [ ]:
df

   A  B  C
0  1  a  0
1  3  b  1
2  2  c  9
3  1  a  0
4  2  b  2

In [ ]:
df.drop_duplicates(subset = ['A','B'], keep = 'last')

   A  B  C
1  3  b  1
2  2  c  9
3  1  a  0
4  2  b  2

In [ ]:
# Last : latest
# First : first punched :: issue with API, Database

### Aggregating Data

In [ ]:
# .groupby(), .agg()

# sum(): Computes the sum of all values in a series or dataframe.
# mean(): Computes the mean (average) of all values in a series or dataframe.
# median(): Computes the median (middle value) of all values in a series or dataframe.
# min(): Computes the minimum value in a series or dataframe.
# max(): Computes the maximum value in a series or dataframe.
# count(): Computes the number of non-null values in a series or dataframe.

In [ ]:
read_imdb_data.head(1)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651

In [ ]:
# read_imdb_data.loc[:,'runtime'].sum()
# read_imdb_data['mean_runtime'] = read_imdb_data.runtime.mean()

In [ ]:
# pd.mean(read_imdb_data['runtime'])

AttributeError: module 'pandas' has no attribute 'mean'

In [ ]:
sum(list(read_imdb_data['runtime'].fillna(0)))

323354.0

#### .groupby()

In [ ]:
read_imdb_data.groupby('original_language')['id'].count().reset_index().sort_values(by = 'id', ascending =False)

   original_language    id
7                 en  2575
11                fr    78
27                ru    47
8                 es    43
13                hi    42
17                ja    37
16                it    24
18                ko    20
2                 cn    20
35                zh    19
5                 de    18
30                ta    16
29                sv     8
25                pt     6
22                nl     6
9                 fa     5
4                 da     5
26                ro     4
32                tr     3
14                hu     3
10                fi     2
31                te     2
24                pl     2
23                no     2
19                ml     2
21                nb     1
20                mr     1
3                 cs     1
28                sr     1
1                 bn     1
15                id     1
6                 el     1
12                he     1
33                ur     1
34                vi     1
0                 ar     1

In [ ]:
read_imdb_data.groupby('original_language')['runtime'].mean().reset_index().sort_values(by='runtime',ascending = False)

   original_language     runtime
20                mr  162.000000
30                ta  159.875000
15                id  150.000000
13                hi  148.880952
31                te  146.000000
19                ml  137.000000
34                vi  135.000000
14                hu  126.000000
1                 bn  125.000000
29                sv  122.375000
5                 de  122.294118
35                zh  121.368421
32                tr  119.000000
18                ko  115.100000
25                pt  114.666667
17                ja  112.972973
26                ro  108.750000
22                nl  107.333333
7                 en  106.984078
11                fr  106.294872
2                 cn  105.450000
4                 da  105.400000
21                nb  103.000000
8                 es  100.372093
10                fi  100.000000
24                pl   99.000000
0                 ar   98.000000
28                sr   97.000000
9                 fa   96.400000
27                ru   95.586957
23                no   95.500000
33                ur   94.000000
16                it   91.625000
6                 el   91.000000
3                 cs   90.000000
12                he   90.000000

In [ ]:
read_imdb_data.groupby('original_language')['revenue'].mean().reset_index().sort_values(by='revenue',ascending = False)

   original_language       revenue
7                 en  7.466591e+07
35                zh  7.037637e+07
32                tr  5.166341e+07
17                ja  3.065180e+07
2                 cn  2.977289e+07
13                hi  2.534637e+07
5                 de  2.053090e+07
11                fr  1.713257e+07
16                it  1.641513e+07
24                pl  1.501083e+07
30                ta  1.470625e+07
18                ko  1.377670e+07
4                 da  1.175709e+07
29                sv  1.163051e+07
12                he  1.112585e+07
25                pt  1.087902e+07
8                 es  8.564790e+06
31                te  8.320425e+06
6                 el  8.000000e+06
27                ru  6.929453e+06
20                mr  4.400000e+06
21                nb  4.159678e+06
15                id  2.627209e+06
22                nl  1.959667e+06
10                fi  1.471932e+06
0                 ar  1.347747e+06
19                ml  1.315000e+06
23                no  1.011068e+06
9                 fa  7.121852e+05
33                ur  6.451350e+05
34                vi  6.390000e+05
1                 bn  5.363640e+05
26                ro  3.399610e+05
14                hu  1.247927e+05
3                 cs  1.739300e+04
28                sr  1.980000e+02

In [ ]:
read_imdb_data.groupby('status')['id'].count()

status
Released    2996
Rumored        4
Name: id, dtype: int64

In [ ]:
# Rows where status = Rumored
# read_imdb_data.loc[read_imdb_data.status =='Rumored',]

In [ ]:
read_imdb_data.groupby(['original_language','status'])['id'].count().reset_index()

#### .agg()

In [ ]:
# .agg()
read_imdb_data.groupby(['original_language','status'])['runtime'].agg(['count','mean','sum']).reset_index()

   original_language    status  count        mean       sum
0                 ar  Released      1   98.000000      98.0
1                 bn  Released      1  125.000000     125.0
2                 cn  Released     20  105.450000    2109.0
3                 cs  Released      1   90.000000      90.0
4                 da  Released      5  105.400000     527.0
5                 de  Released     17  122.294118    2079.0
6                 el  Released      1   91.000000      91.0
7                 en  Released   2571  107.030338  275175.0
8                 en   Rumored      4   77.250000     309.0
9                 es  Released     43  100.372093    4316.0
10                fa  Released      5   96.400000     482.0
11                fi  Released      2  100.000000     200.0
12                fr  Released     78  106.294872    8291.0
13                he  Released      1   90.000000      90.0
14                hi  Released     42  148.880952    6253.0
15                hu  Released      3  126.000000     378.0
16                id  Released      1  150.000000     150.0
17                it  Released     24   91.625000    2199.0
18                ja  Released     37  112.972973    4180.0
19                ko  Released     20  115.100000    2302.0
20                ml  Released      2  137.000000     274.0
21                mr  Released      1  162.000000     162.0
22                nb  Released      1  103.000000     103.0
23                nl  Released      6  107.333333     644.0
24                no  Released      2   95.500000     191.0
25                pl  Released      2   99.000000     198.0
26                pt  Released      6  114.666667     688.0
27                ro  Released      4  108.750000     435.0
28                ru  Released     46   95.586957    4397.0
29                sr  Released      1   97.000000      97.0
30                sv  Released      8  122.375000     979.0
31                ta  Released     16  159.875000    2558.0
32                te  Released      2  146.000000     292.0
33                tr  Released      3  119.000000     357.0
34                ur  Released      1   94.000000      94.0
35                vi  Released      1  135.000000     135.0
36                zh  Released     19  121.368421    2306.0

In [ ]:
read_imdb_data.groupby(['status', 'original_language']).agg({'runtime':"mean",'revenue': "max",'imdb_id':"count"}).reset_index()

      status original_language     runtime     revenue  imdb_id
0   Released                ar   98.000000     1347747        1
1   Released                bn  125.000000      536364        1
2   Released                cn  105.450000   156844753       20
3   Released                cs   90.000000       17393        1
4   Released                da  105.400000    42070000        5
5   Released                de  122.294118    92180910       18
6   Released                el   91.000000     8000000        1
7   Released                en  107.030338  1519557910     2571
8   Released                es  100.372093    67872296       43
9   Released                fa   96.400000     2402067        5
10  Released                fi  100.000000     2411594        2
11  Released                fr  106.294872   426480871       78
12  Released                he   90.000000    11125849        1
13  Released                hi  148.880952   310000000       42
14  Released                hu  126.000000      282358        3
15  Released                id  150.000000     2627209        1
16  Released                it   91.625000   229400000       24
17  Released                ja  112.972973   133949270       37
18  Released                ko  115.100000    86758912       20
19  Released                ml  137.000000     2500000        2
20  Released                mr  162.000000     4400000        1
21  Released                nb  103.000000     4159678        1
22  Released                nl  107.333333     5475058        6
23  Released                no   95.500000     1984662        2
24  Released                pl   99.000000    15298355        2
25  Released                pt  114.666667    56702901        6
26  Released                ro  108.750000     1185783        4
27  Released                ru   95.586957    55635037       47
28  Released                sr   97.000000         198        1
29  Released                sv  122.375000    66995253        8
30  Released                ta  159.875000    62000000       16
31  Released                te  146.000000    14000000        2
32  Released                tr  119.000000   149521495        3
33  Released                ur   94.000000      645135        1
34  Released                vi  135.000000      639000        1
35  Released                zh  121.368421   385284817       19
36   Rumored                en   77.250000    13418091        4

### Joining Dataframes

In [ ]:
# .merge(), .concat()
# Inner join, left join, right join, outer join
# pd.concat( [df] , axis)

# pd.merge(df1, df2 ,on,how)

#### .concat()

In [ ]:
# read_imdb_data.original_language.value_counts()

In [ ]:
read_imdb_data_en = read_imdb_data.loc[read_imdb_data.original_language == 'en',]
read_imdb_data_other = read_imdb_data.loc[read_imdb_data.original_language != 'en',]

In [ ]:
read_imdb_data_en.shape

(2575, 24)

In [ ]:
read_imdb_data_other.shape

(425, 24)

In [ ]:
df_final = pd.concat([read_imdb_data_en,read_imdb_data_other],axis = 0)

In [ ]:
df_final.shape

(3000, 24)

In [ ]:
data1 = {'ID': [1, 2, 3],
         'Name': ['John', 'Alice', 'Bob'],
         'Age': [30, 25, 35]}
df1 = pd.DataFrame(data1)
df1

   ID   Name  Age
0   1   John   30
1   2  Alice   25
2   3    Bob   35

In [ ]:
data2 = {'Salary': [50000, 60000, 70000]}
df2 = pd.DataFrame(data2)
df2

   Salary
0   50000
1   60000
2   70000

In [ ]:
pd.concat([df1,df2],axis = 1)

   ID   Name  Age  Salary
0   1   John   30   50000
1   2  Alice   25   60000
2   3    Bob   35   70000

#### .merge()

In [ ]:
data1 = {'ID': [1, 2, 3, 4],
         'Name': ['John', 'Alice', 'Bob', 'Charlie'],
         'Age': [30, 25, 35, 40]}
df1 = pd.DataFrame(data1)
data2 = {'salary_ID': [2, 3, 5, 6],
         'Salary': [50000, 60000, 70000, 80000]}
df2 = pd.DataFrame(data2)
print(df1)
print(df2)

   ID     Name  Age
0   1     John   30
1   2    Alice   25
2   3      Bob   35
3   4  Charlie   40
   salary_ID  Salary
0          2   50000
1          3   60000
2          5   70000
3          6   80000

In [ ]:
# Inner
pd.merge(df1,df2, left_on = 'ID', right_on = 'salary_ID', how ='inner')

   ID   Name  Age  salary_ID  Salary
0   2  Alice   25          2   50000
1   3    Bob   35          3   60000

In [ ]:
# left
pd.merge(df1,df2, left_on = 'ID', right_on = 'salary_ID', how ='left')

   ID     Name  Age  salary_ID   Salary
0   1     John   30        NaN      NaN
1   2    Alice   25        2.0  50000.0
2   3      Bob   35        3.0  60000.0
3   4  Charlie   40        NaN      NaN

In [ ]:
# right
pd.merge(df1,df2, left_on = 'ID', right_on = 'salary_ID', how ='right')

    ID   Name   Age  salary_ID  Salary
0  2.0  Alice  25.0          2   50000
1  3.0    Bob  35.0          3   60000
2  NaN    NaN   NaN          5   70000
3  NaN    NaN   NaN          6   80000

In [ ]:
# outer
pd.merge(df1,df2, left_on = 'ID', right_on = 'salary_ID', how ='outer')

    ID     Name   Age  salary_ID   Salary
0  1.0     John  30.0        NaN      NaN
1  2.0    Alice  25.0        2.0  50000.0
2  3.0      Bob  35.0        3.0  60000.0
3  4.0  Charlie  40.0        NaN      NaN
4  NaN      NaN   NaN        5.0  70000.0
5  NaN      NaN   NaN        6.0  80000.0

In [ ]:
# Cross join :: Try to search for it.
# Key
df1['key'] = 1
df2['key'] = 1
pd.merge(df1,df2, on = 'key', how = 'outer')

    ID     Name  Age  key  salary_ID  Salary
0    1     John   30    1          2   50000
1    1     John   30    1          3   60000
2    1     John   30    1          5   70000
3    1     John   30    1          6   80000
4    2    Alice   25    1          2   50000
5    2    Alice   25    1          3   60000
6    2    Alice   25    1          5   70000
7    2    Alice   25    1          6   80000
8    3      Bob   35    1          2   50000
9    3      Bob   35    1          3   60000
10   3      Bob   35    1          5   70000
11   3      Bob   35    1          6   80000
12   4  Charlie   40    1          2   50000
13   4  Charlie   40    1          3   60000
14   4  Charlie   40    1          5   70000
15   4  Charlie   40    1          6   80000

### .replace(),.apply()

In [ ]:
read_imdb_data.head(1)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651

In [ ]:
read_imdb_data.original_language.value_counts().reset_index()

   original_language  count
0                 en   2575
1                 fr     78
2                 ru     47
3                 es     43
4                 hi     42
5                 ja     37
6                 it     24
7                 cn     20
8                 ko     20
9                 zh     19
10                de     18
11                ta     16
12                sv      8
13                nl      6
14                pt      6
15                fa      5
16                da      5
17                ro      4
18                hu      3
19                tr      3
20                no      2
21                ml      2
22                pl      2
23                te      2
24                fi      2
25                ur      1
26                he      1
27                el      1
28                ar      1
29                nb      1
30                vi      1
31                mr      1
32                cs      1
33                sr      1
34                bn      1
35                id      1

In [ ]:
read_imdb_data.original_language.replace({'en':'english','hi':'hindi'})

0       english
1       english
2       english
3         hindi
4            ko
         ...
2995    english
2996         sv
2997    english
2998    english
2999    english
Name: original_language, Length: 3000, dtype: object

In [ ]:
### how do we replace rest to others? --> We use apply with custom function

#### .apply()

In [ ]:
read_imdb_data.original_language

0       en
1       en
2       en
3       hi
4       ko
        ..
2995    en
2996    sv
2997    en
2998    en
2999    en
Name: original_language, Length: 3000, dtype: object

In [ ]:
def lang_map(l): # custom function
  if l == 'en':
    return 'english'
  elif l == 'hi':
    return 'hindi'
  else:
    return 'others'

lang_map(l = 'en')

'english'

In [ ]:
read_imdb_data.original_language = read_imdb_data.original_language.apply(lang_map) # Applied to each element

In [ ]:
def first_letter(s):
  return s[0]

In [ ]:
read_imdb_data.original_language.apply(first_letter)

0       e
1       e
2       e
3       h
4       k
       ..
2995    e
2996    s
2997    e
2998    e
2999    e
Name: original_language, Length: 3000, dtype: object

In [ ]:
def lang_chang(l):
  if l == 'en':
    return 'english'
  elif l == 'hi':
    return 'hindi'
  else:
    return l

In [ ]:
read_imdb_data.original_language.apply(lang_chang)

0       english
1       english
2       english
3         hindi
4            ko
         ...
2995    english
2996         sv
2997    english
2998    english
2999    english
Name: original_language, Length: 3000, dtype: object

### Dealing with Strings, Datetime & Json data in column

##### Strings

In [ ]:
# Important functions
# str.contains(), str.find(''),str.replace(old,new), str.split('delimiter'), str.strip(), str.extract() and str.extractall()

In [ ]:
read_imdb_data.head(1)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651

In [ ]:
read_imdb_data.title

0                         Hot Tub Time Machine 2
1       The Princess Diaries 2: Royal Engagement
2                                       Whiplash
3                                        Kahaani
4                                     Marine Boy
                          ...
2995                                     Chasers
2996                            We Are the Best!
2997                     The Long Kiss Goodnight
2998                            Along Came Polly
2999                                   Abduction
Name: title, Length: 3000, dtype: object

In [ ]:
# str.contains()
# read_imdb_data.title.str.contains('Time') # Exact match as substring
# read_imdb_data.title.str.contains(r'[0-9]{1,}') # Match as regex

In [ ]:
# .loc[row_name,column_name]
# .iloc[row_index,column_index]

In [ ]:
# read_imdb_data.loc[read_imdb_data.title.str.contains('Time'),]

In [ ]:
read_imdb_data.title

0                         Hot Tub Time Machine 2
1       The Princess Diaries 2: Royal Engagement
2                                       Whiplash
3                                        Kahaani
4                                     Marine Boy
                          ...
2995                                     Chasers
2996                            We Are the Best!
2997                     The Long Kiss Goodnight
2998                            Along Came Polly
2999                                   Abduction
Name: title, Length: 3000, dtype: object

In [ ]:
# str.find('')
# read_imdb_data.title.str.find('h') # -1 if not found , otherwise first occurance.

0       16
1        1
2        1
3        2
4       -1
        ..
2995     1
2996     8
2997     1
2998    -1
2999    -1
Name: title, Length: 3000, dtype: int64

In [ ]:
# str.replace(old,new)
# read_imdb_data.title.str.replace('Time','TIME') # Replace Exact match as substring
# read_imdb_data.title.str.replace(r'[0-9]{1,}','&', regex=True) # Match as regex

0                         Hot Tub Time Machine &
1       The Princess Diaries &: Royal Engagement
2                                       Whiplash
3                                        Kahaani
4                                     Marine Boy
                          ...
2995                                     Chasers
2996                            We Are the Best!
2997                     The Long Kiss Goodnight
2998                            Along Came Polly
2999                                   Abduction
Name: title, Length: 3000, dtype: object

In [ ]:
read_imdb_data.title

0                         Hot Tub Time Machine 2
1       The Princess Diaries 2: Royal Engagement
2                                       Whiplash
3                                        Kahaani
4                                     Marine Boy
                          ...
2995                                     Chasers
2996                            We Are the Best!
2997                     The Long Kiss Goodnight
2998                            Along Came Polly
2999                                   Abduction
Name: title, Length: 3000, dtype: object

In [ ]:
def get_3_value(x):
  if len(x) < 3:
    return x
  else:
    return x[2]

In [ ]:
read_imdb_data.title.str.split(' ')

In [ ]:
# str.split('delimiter')
read_imdb_data.title.str.split(' ').apply(get_3_value) # Splits the string and converts it to list

0                Time
1             Diaries
2          [Whiplash]
3           [Kahaani]
4       [Marine, Boy]
            ...
2995        [Chasers]
2996              the
2997             Kiss
2998            Polly
2999      [Abduction]
Name: title, Length: 3000, dtype: object

In [ ]:
df = pd.read_csv()
# df.drop_duplicates()
# run .strip for each categorical column

In [ ]:
# str.strip() --> Strips the extra space
read_imdb_data.title.str.strip()

0                         Hot Tub Time Machine 2
1       The Princess Diaries 2: Royal Engagement
2                                       Whiplash
3                                        Kahaani
4                                     Marine Boy
                          ...
2995                                     Chasers
2996                            We Are the Best!
2997                     The Long Kiss Goodnight
2998                            Along Came Polly
2999                                   Abduction
Name: title, Length: 3000, dtype: object

In [ ]:
# My email id is alok@febfwjf.com
# ravi@jefrjnfre;f.com is my email id.

In [ ]:
read_imdb_data.title

0                         Hot Tub Time Machine 2
1       The Princess Diaries 2: Royal Engagement
2                                       Whiplash
3                                        Kahaani
4                                     Marine Boy
                          ...
2995                                     Chasers
2996                            We Are the Best!
2997                     The Long Kiss Goodnight
2998                            Along Came Polly
2999                                   Abduction
Name: title, Length: 3000, dtype: object

In [ ]:
# str.contains('Time') and str.contains('Machine')

In [ ]:
read_imdb_data.title.str.contains(r'([0-9]{1,})')

<ipython-input-72-5667d63e85b8>:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  read_imdb_data.title.str.contains(r'([0-9]{1,})')

0        True
1        True
2       False
3       False
4       False
        ...
2995    False
2996    False
2997    False
2998    False
2999    False
Name: title, Length: 3000, dtype: bool

In [ ]:
df1 = read_imdb_data.title.str.extract(r'([0-9]{1,})').reset_index()
df1.loc[df1.index ==2960,]

      index  0
2960   2960  4

In [ ]:
read_imdb_data.loc[21,]

id                                                                      22
belongs_to_collection    [{'id': 9735, 'name': 'Friday the 13th Collect...
budget                                                             4000000
genres                   [{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...
homepage                                                               NaN
imdb_id                                                          tt0083972
original_language                                                       en
original_title                                    Friday the 13th Part III
overview                 An idyllic summer turns into a nightmare of un...
popularity                                                         7.99229
poster_path                               /5wg2NZyIhcMbIBAahBODXHyJ54S.jpg
production_companies     [{'name': 'Paramount Pictures', 'id': 4}, {'na...
production_countries     [{'iso_3166_1': 'US', 'name': 'United States o...
release_date                                                       8/13/82
runtime                                                               95.0
spoken_languages                  [{'iso_639_1': 'en', 'name': 'English'}]
status                                                            Released
tagline                       There's nowhere to hide. We dare you to try.
title                                             Friday the 13th Part III
Keywords                 [{'id': 1889, 'name': 'lake'}, {'id': 5767, 'n...
cast                     [{'cast_id': 1, 'character': 'Chris Higgins', ...
crew                     [{'credit_id': '52fe4523c3a36847f80be885', 'de...
revenue                                                           36690067
Name: 21, dtype: object

In [ ]:
data = [{'name':'John', 'about':'My contact detail is 9876543210, Call me for the house repair'},
        {'name':'Albert','about':'4567890123 is my contact detail, you can contact me for the problem with electricty, my alternate number is 6789012343'}]

df = pd.DataFrame(data)
df

     name                                              about
0    John  My contact detail is 9876543210, Call me for t...
1  Albert  4567890123 is my contact detail, you can conta...

In [ ]:
df.about.str.extract(r'([0-9]{10})')

            0
0  9876543210
1  4567890123

In [ ]:
df.about.str.extractall(r'([0-9]{10})')

                  0
  match
0 0      9876543210
1 0      4567890123
  1      6789012343

In [ ]:
# str.extract() and str.extractall() --> Extracts the substring based on regex pattern
# read_imdb_data.title.str.extract(r'([0-9]{1,})') # Extracts first match
read_imdb_data.title.str.extractall(r'([0-9]{1,})').reset_index() # Extracts all matches

     level_0  match   0
0          0      0   2
1          1      0   2
2         19      0   2
3         21      0  13
4         33      0   2
..       ...    ...  ..
202     2958      1   3
203     2960      0   4
204     2960      1   3
205     2960      2   2
206     2960      3   1

[207 rows x 3 columns]

In [ ]:
read_imdb_data.loc[2960,'title']

'4.3.2.1'

##### Datetime

In [ ]:
# Converting String to Datetime
# Extracting components from the datetime
# Create a timedelta object representing a duration : Adding or substracting some year,months, days, hours,minutes,etc
# Subtracting two datetime
# Putting filter on datetime

In [ ]:
read_imdb_data.head(1)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,english,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651

In [ ]:
read_imdb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   object
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
dtypes: float64(2), int64(3), object(18)
memory usage: 539.2+ KB

In [ ]:
read_imdb_data['release_date'].head(5)

0     2/20/15
1      8/6/04
2    10/10/14
3      3/9/12
4      2/5/09
Name: release_date, dtype: object

In [ ]:
data = [{'index':0,'date':'01-09-24'},{'index':1,'date':'01-11-22'}]
df = pd.DataFrame(data)
df

   index      date
0      0  01-09-24
1      1  01-11-22

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   2 non-null      int64
 1   date    2 non-null      object
dtypes: int64(1), object(1)
memory usage: 160.0+ bytes

In [ ]:
df.date = pd.to_datetime(df.date,format= '%d-%m-%y')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   2 non-null      int64
 1   date    2 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1)
memory usage: 160.0 bytes

In [ ]:
# Converting String to Datetime
# .to_datetime
# Ref : https://www.geeksforgeeks.org/python-datetime-strptime-function/

read_imdb_data.release_date = pd.to_datetime(read_imdb_data.release_date,format= '%m/%d/%y')

In [ ]:
read_imdb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   datetime64[ns]
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(3), object(17)
memory usage: 539.2+ KB

In [ ]:
read_imdb_data.head(1)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2015-02-20,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651

In [ ]:
read_imdb_data.release_date

0      2015-02-20
1      2004-08-06
2      2014-10-10
3      2012-03-09
4      2009-02-05
          ...
2995   1994-04-22
2996   2013-03-28
2997   1996-10-11
2998   2004-01-16
2999   2011-09-22
Name: release_date, Length: 3000, dtype: datetime64[ns]

In [ ]:
# Extracting components from the datetime
# dt. --> day,date, year, month,week, hour, day_name(), dayofyear,weekday(Monday=0, Sunday=6)
read_imdb_data['release_day'] = read_imdb_data.release_date.dt.day_name()

In [ ]:
read_imdb_data['release_day'].head()

0      Friday
1      Friday
2      Friday
3      Friday
4    Thursday
Name: release_day, dtype: object

In [ ]:
read_imdb_data.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue',
       'release_day'],
      dtype='object')

In [ ]:
# read_imdb_data.loc[:,['belongs_to_collection','id',  'budget', 'genres', 'homepage',
#        'imdb_id', 'original_language', 'original_title', 'overview',
#        'popularity', 'poster_path', 'production_companies',
#        'production_countries', 'release_date', 'runtime', 'spoken_languages',
#        'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue',
#        'release_day']]

In [ ]:
read_imdb_data.head(1)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,release_day
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,Friday

In [ ]:
read_imdb_data.release_date.head(1)

0   2015-02-20
Name: release_date, dtype: datetime64[ns]

In [ ]:
read_imdb_data.release_date

0      2015-02-20
1      2004-08-06
2      2014-10-10
3      2012-03-09
4      2009-02-05
          ...
2995   1994-04-22
2996   2013-03-28
2997   1996-10-11
2998   2004-01-16
2999   2011-09-22
Name: release_date, Length: 3000, dtype: datetime64[ns]

In [ ]:
# Create a timedelta object representing a duration : Adding or substracting some [weeks, days, hours, minutes, seconds, milliseconds, microseconds, nanoseconds]
# pd.Timedelta(days=2)
read_imdb_data.release_date - pd.Timedelta(weeks = 1)

0      2015-02-13
1      2004-07-30
2      2014-10-03
3      2012-03-02
4      2009-01-29
          ...
2995   1994-04-15
2996   2013-03-21
2997   1996-10-04
2998   2004-01-09
2999   2011-09-15
Name: release_date, Length: 3000, dtype: datetime64[ns]

In [ ]:
read_imdb_data.loc[:,'release_date_plus2d'] = read_imdb_data.release_date + pd.Timedelta(days = 2)

In [ ]:
(read_imdb_data.release_date_plus2d - read_imdb_data.release_date).dt.days

0       2
1       2
2       2
3       2
4       2
       ..
2995    2
2996    2
2997    2
2998    2
2999    2
Length: 3000, dtype: int64

In [ ]:
# Subtracting two datetime
read_imdb_data.loc[:,'date_diff'] = (read_imdb_data.release_date_plus2d - read_imdb_data.release_date).dt.days

In [ ]:
read_imdb_data.head(1)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,release_date_plus2d,date_diff
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,2015-02-22,2

In [ ]:
# Putting filter on datetime
read_imdb_data.loc[read_imdb_data.release_date > '2019-01-01',].sort_values(by='release_date', ascending = True)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,release_day,release_date_plus2d
1763,1764,NaN,250000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0012349,en,The Kid,Considered one of Charlie Chaplin's best films...,8.168456,...,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,6 reels of Joy.,The Kid,"[{'id': 290, 'name': 'angel'}, {'id': 1252, 'n...","[{'cast_id': 10, 'character': 'A Tramp', 'cred...","[{'credit_id': '52fe43269251416c75005605', 'de...",2500000,Thursday,2021-01-23
2992,2993,NaN,1135654,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,tt0015400,en,The Thief of Bagdad,A recalcitrant thief vies with a duplicitous M...,3.878515,...,"[{'iso_639_1': 'xx', 'name': 'No Language'}]",Released,"""Happiness Must Be Earned""",The Thief of Bagdad,"[{'id': 255, 'name': 'male nudity'}, {'id': 14...","[{'cast_id': 3, 'character': 'The Thief of Bag...","[{'credit_id': '52fe45bec3a368484e06c70b', 'de...",1213880,Monday,2024-03-20
1917,1918,NaN,592,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",NaN,tt0016104,en,The Merry Widow,Prince Danilo falls in love with dancer Sally ...,0.286719,...,NaN,Released,NaN,The Merry Widow,"[{'id': 1691, 'name': 'dance'}, {'id': 10181, ...","[{'cast_id': 2, 'character': ""Sally O'Hara"", '...","[{'credit_id': '57351170c3a36802410000d5', 'de...",1,Tuesday,2025-08-28
1361,1362,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",NaN,tt0015648,ru,Броненосец «Потёмкин»,A dramatized account of a great Russian naval ...,12.912845,...,"[{'iso_639_1': 'ru', 'name': 'Pусский'}]",Released,"Revolution is the only lawful, equal, effectua...",Battleship Potemkin,"[{'id': 1816, 'name': 'staircase'}, {'id': 323...","[{'cast_id': 8, 'character': 'Grigory Vakulinc...","[{'credit_id': '52fe4263c3a36847f801a8cf', 'de...",45100,Wednesday,2025-12-26
2680,2681,NaN,463455,"[{'id': 18, 'name': 'Drama'}]",NaN,tt0017423,en,Sparrows,Evil Mr.Grimes keeps a rag-tag bunch orphans o...,0.445526,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Sparrows,"[{'id': 1930, 'name': 'kidnapping'}, {'id': 49...","[{'cast_id': 2, 'character': 'Molly', 'credit_...","[{'credit_id': '52fe48a1c3a368484e102bd9', 'de...",966878,Thursday,2026-05-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1034,1035,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt0063518,en,Romeo and Juliet,Director Franco Zeffirelli's beloved version o...,6.990990,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No ordinary love story...,Romeo and Juliet,"[{'id': 255, 'name': 'male nudity'}, {'id': 16...","[{'cast_id': 6, 'character': 'Romeo', 'credit_...","[{'credit_id': '52fe4435c3a36847f80889c3', 'de...",38901218,Monday,2068-04-04
2147,2148,"[{'id': 264338, 'name': ""Rosemary's Baby Colle...",3200000,"[{'id': 27, 'name': 'Horror'}, {'id': 18, 'nam...",NaN,tt0063522,en,Rosemary's Baby,A young couple moves into an infamous New York...,11.504558,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Pray for Rosemary's Baby,Rosemary's Baby,"[{'id': 8685, 'name': 'anti-christ'}, {'id': 1...","[{'cast_id': 15, 'character': 'Rosemary Woodho...","[{'credit_id': '52fe4279c3a36847f8021573', 'de...",33395426,Tuesday,2068-06-14
140,141,NaN,14320000,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt0063642,en,Star!,Gertrude Lawrence rises to stage stardom at th...,0.585397,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Happiness is a girl called Julie!,Star!,"[{'id': 4344, 'name': 'musical'}, {'id': 12990...","[{'cast_id': 3, 'character': 'Gertrude Lawrenc...","[{'credit_id': '52fe484bc3a36847f81602c9', 'de...",14000000,Wednesday,2068-07-20
647,648,NaN,9000000,"[{'id': 878, 'name': 'Science Fiction'}]",NaN,tt0062711,en,Barbarella,"In the far future, a highly sexual woman is ta...",14.304205,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,See Barbarella do her thing!,Barbarella,"[{'id': 9835, 'name': 'sexual fantasy'}, {'id'...","[{'cast_id': 2, 'character': 'Barbarella', 'cr...","[{'credit_id': '52fe4491c3a36847f809d5ab', 'de...",2500000,Wednesday,2068-10-12
2649,2650,NaN,1455000,"[{'id': 37, 'name': 'Western'}]",NaN,tt0063592,en,Shalako,"Sean Connery is Shalako, a guide in the old We...",6.229674,...,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,Sean Connery is Shalako! Shalako means action!...,Shalako,"[{'id': 10322, 'name': 'native american'}, {'i...","[{'cast_id': 3, 'character': ""Moses Zebulon 'S...","[{'credit_id': '52fe47029251416c9106740b', 'de...",2620000,Tuesday,2068-11-08

##### Dealing with JSON

In [ ]:
# pd.json_normalize()

In [ ]:
pd.json_normalize([{'a':1,'b':4},{'a':9,'b':7}])

   a  b
0  1  4
1  9  7

In [ ]:
# pd.DataFrame([{'a':1,'b':4},{'a':9,'b':7}])

   a  b
0  1  4
1  9  7

In [ ]:
pd.json_normalize([{'a':1,'b':{'c':2,'d':3}},{'a':9,'b':{'c':10,'d':11,'e':12}}])

   a  b.c  b.d   b.e
0  1    2    3   NaN
1  9   10   11  12.0

In [ ]:
# pd.json_normalize([{'a':1,'b':{'c':2,'d':3}},{'a':9,'b':{'c':10,'d':11,'e':12}}])

In [ ]:
read_imdb_data.head(1)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,release_date_plus2d,date_diff
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,2015-02-22,2

In [ ]:
read_imdb_data.genres[0]

"[{'id': 35, 'name': 'Comedy'}]"

In [ ]:
pd.json_normalize(eval(read_imdb_data.genres[0]))

   id    name
0  35  Comedy

In [ ]:
# Steps to take :
# 1. First implement eval to convert from str to Json (list of dict)
# 2. pd.json_normalize to make it dataframe
# 3. get the name column as series, convert to list and join comma separated

In [ ]:
read_imdb_data.genres[0]

"[{'id': 35, 'name': 'Comedy'}]"

In [ ]:
# extract Genre for the movies
# Custom function
def parse_json(s,key):
  try:
    j = eval(s) # list of dictionaries
    return ','.join(list(pd.json_normalize(j)[key]))
  except:
    return s

In [ ]:
read_imdb_data.head(2)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435

In [ ]:
# list(read_imdb_data.genres[1])

In [ ]:
j = eval(read_imdb_data.genres[1])

In [ ]:
pd.json_normalize(j)

      id     name
0     35   Comedy
1     18    Drama
2  10751   Family
3  10749  Romance

In [ ]:
list(pd.json_normalize(j)['name'])

['Comedy', 'Drama', 'Family', 'Romance']

In [ ]:
# Comedy,Drama,Family,Romance
','.join(list(pd.json_normalize(j)['name']))

'Comedy,Drama,Family,Romance'

In [ ]:
# ','.join(list(pd.json_normalize(j)['name']))

'Comedy,Drama,Family,Romance'

In [ ]:
# ','.join(list(pd.json_normalize(j)[key]))

In [ ]:
# parse_json(s = read_imdb_data.genres[0],key = 'name')

'Comedy'

In [ ]:
read_imdb_data.genres.apply(parse_json,key = 'name')

0                              Comedy
1         Comedy,Drama,Family,Romance
2                               Drama
3                      Thriller,Drama
4                     Action,Thriller
                    ...
2995                   Comedy,Romance
2996                      Drama,Music
2997    Crime,Action,Mystery,Thriller
2998                   Comedy,Romance
2999          Thriller,Action,Mystery
Name: genres, Length: 3000, dtype: object

In [ ]:
read_imdb_data.head(1)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651

In [ ]:
read_imdb_data.spoken_languages.head(10)

0             [{'iso_639_1': 'en', 'name': 'English'}]
1             [{'iso_639_1': 'en', 'name': 'English'}]
2             [{'iso_639_1': 'en', 'name': 'English'}]
3    [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
4             [{'iso_639_1': 'ko', 'name': '한국어/조선말'}]
5             [{'iso_639_1': 'en', 'name': 'English'}]
6             [{'iso_639_1': 'en', 'name': 'English'}]
7    [{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...
8             [{'iso_639_1': 'en', 'name': 'English'}]
9             [{'iso_639_1': 'en', 'name': 'English'}]
Name: spoken_languages, dtype: object

In [ ]:
read_imdb_data.spoken_languages.apply(parse_json,key = 'iso_639_1')

0          en
1          en
2          en
3       en,hi
4          ko
        ...
2995       en
2996       sv
2997       en
2998       en
2999       en
Name: spoken_languages, Length: 3000, dtype: object

In [ ]:
# read_imdb_data.cast.apply(parse_json,key = 'name')

0       Rob Corddry,Craig Robinson,Clark Duke,Adam Sco...
1       Anne Hathaway,Julie Andrews,H√©ctor Elizondo,J...
2       Miles Teller,J.K. Simmons,Melissa Benoist,Aust...
3       Vidya Balan,Nawazuddin Siddiqui,Parambrata Cha...
4       Kim Kang-woo,Jo Jae-hyeon,Park Si-yeon,Kim Joo...
                              ...
2995    Tom Berenger,William McNamara,–≠—Ä–∏–∫–∞ –≠–ª–...
2996    Mira Barkhammar,Mira Grosin,Liv LeMoyne,David ...
2997    Geena Davis,Samuel L. Jackson,Yvonne Zima,Crai...
2998    Ben Stiller,Jennifer Aniston,Philip Seymour Ho...
2999    Taylor Lautner,Lily Collins,Alfred Molina,Jaso...
Name: cast, Length: 3000, dtype: object

### Reshaping data

In [ ]:
# .pivot(), .crosstab(), .astype()

In [ ]:
read_imdb_data.head(1)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651

In [ ]:
read_imdb_data.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [ ]:
read_imdb_data.groupby(['original_language','release_date']).agg({'runtime':'mean','revenue':'mean'}).reset_index().sort_values('original_language')

     original_language release_date  runtime     revenue
0              english   1969-01-01    149.0  20000000.0
1422           english   2010-04-23    101.5  38750433.5
1421           english   2010-04-02     92.0  39340177.0
1420           english   2010-04-01    118.0   3878993.0
1419           english   2010-03-22    117.0  96188903.0
...                ...          ...      ...         ...
2278            others   2005-05-02    117.0  36000000.0
2277            others   2005-03-05    126.0   8262833.0
2276            others   2004-12-23     72.0   1730000.0
2285            others   2005-08-04    133.0  33579813.0
2528            others   2068-03-22    107.0     44566.0

[2529 rows x 4 columns]

In [ ]:
# df.pivot(index='col1', columns='col2', values=['col']) # note: index & column must be unique
# Function used in combination with group by

In [ ]:
read_imdb_data.groupby(['original_language','release_date']).agg({'revenue':'mean'}).reset_index()

     original_language release_date      revenue
0              english   1969-01-01   20000000.0
1              english   1969-06-17     638641.0
2              english   1969-09-23  102308889.0
3              english   1969-12-12   33208099.0
4              english   1969-12-18    6000000.0
...                ...          ...          ...
2524            others   2060-05-24    8000000.0
2525            others   2064-08-05     182857.0
2526            others   2066-04-05      17277.0
2527            others   2066-09-08     921548.0
2528            others   2068-03-22      44566.0

[2529 rows x 3 columns]

In [ ]:
read_imdb_data_grpd_pivot

                  release_date      revenue
original_language                   english hindi    others
0                   1969-01-01   20000000.0   NaN       NaN
1                   1969-06-17     638641.0   NaN       NaN
2                   1969-09-10          NaN   NaN  741766.0
3                   1969-09-23  102308889.0   NaN       NaN
4                   1969-12-12   33208099.0   NaN       NaN
...                        ...          ...   ...       ...
2393                2068-04-02   38901218.0   NaN       NaN
2394                2068-06-12   33395426.0   NaN       NaN
2395                2068-07-18   14000000.0   NaN       NaN
2396                2068-10-10    2500000.0   NaN       NaN
2397                2068-11-06    2620000.0   NaN       NaN

[2398 rows x 4 columns]

In [ ]:
read_imdb_data.groupby(['original_language','release_date']).agg({'revenue':'mean'})

                                    revenue
original_language release_date
english           1969-01-01     20000000.0
                  1969-06-17       638641.0
                  1969-09-23    102308889.0
                  1969-12-12     33208099.0
                  1969-12-18      6000000.0
...                                     ...
others            2060-05-24      8000000.0
                  2064-08-05       182857.0
                  2066-04-05        17277.0
                  2066-09-08       921548.0
                  2068-03-22        44566.0

[2529 rows x 1 columns]

In [ ]:
read_imdb_data_grpd = read_imdb_data.groupby(['original_language','release_date']).agg({'revenue':'mean'}).reset_index()

In [ ]:
read_imdb_data_grpd_pivot = read_imdb_data_grpd.pivot(index = 'release_date',columns = 'original_language', values = [	'revenue']).reset_index()

In [ ]:
read_imdb_data_grpd_pivot

                  release_date      revenue
original_language                   english hindi    others
0                   1969-01-01   20000000.0   NaN       NaN
1                   1969-06-17     638641.0   NaN       NaN
2                   1969-09-10          NaN   NaN  741766.0
3                   1969-09-23  102308889.0   NaN       NaN
4                   1969-12-12   33208099.0   NaN       NaN
...                        ...          ...   ...       ...
2393                2068-04-02   38901218.0   NaN       NaN
2394                2068-06-12   33395426.0   NaN       NaN
2395                2068-07-18   14000000.0   NaN       NaN
2396                2068-10-10    2500000.0   NaN       NaN
2397                2068-11-06    2620000.0   NaN       NaN

[2398 rows x 4 columns]

In [ ]:
read_imdb_data_grpd_pivot.columns

MultiIndex([('release_date',        ''),
            (     'runtime', 'english'),
            (     'runtime',   'hindi'),
            (     'runtime',  'others'),
            (     'revenue', 'english'),
            (     'revenue',   'hindi'),
            (     'revenue',  'others')],
           names=[None, 'original_language'])

In [ ]:
read_imdb_data_grpd_pivot.head()

                  release_date runtime                   revenue        \
original_language              english hindi others      english hindi
0                   1969-01-01   149.0   NaN    NaN   20000000.0   NaN
1                   1969-06-17   145.0   NaN    NaN     638641.0   NaN
2                   1969-09-10     NaN   NaN  145.0          NaN   NaN
3                   1969-09-23   110.0   NaN    NaN  102308889.0   NaN
4                   1969-12-12   146.0   NaN    NaN   33208099.0   NaN


original_language    others
0                       NaN
1                       NaN
2                  741766.0
3                       NaN
4                       NaN

In [ ]:
read_imdb_data_grpd_pivot.loc[:30,[('runtime', 'others'),('revenue','hindi')]]

                  runtime revenue
original_language  others   hindi
0                     NaN     NaN
1                     NaN     NaN
2                   145.0     NaN
3                     NaN     NaN
4                     NaN     NaN
5                     NaN     NaN
6                     NaN     NaN
7                     NaN     NaN
8                     NaN     NaN
9                   126.0     NaN
10                    NaN     NaN
11                    NaN     NaN
12                    NaN     NaN
13                    NaN     NaN
14                    NaN     NaN
15                    NaN     NaN
16                    NaN     NaN
17                    NaN     NaN
18                    NaN     NaN
19                    NaN     NaN
20                    NaN     NaN
21                    NaN     NaN
22                    NaN     NaN
23                  101.0     NaN
24                    NaN     NaN
25                    NaN     NaN
26                    NaN     NaN
27                    NaN     NaN
28                   98.0     NaN
29                  129.0     NaN
30                  115.0     NaN

In [ ]:
# Accuracy --> Actual vs Predicted
# heatmap --> For categorical vs categorical Variable

In [ ]:
read_imdb_data.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,english,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2015-02-20,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,english,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,2004-08-06,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,english,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,2014-10-10,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hindi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,2012-03-09,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,others,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2009-02-05,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970

In [ ]:
read_imdb_data.groupby(['release_date','original_language'])['id'].count().reset_index()

     release_date original_language  id
0      1969-01-01           english   1
1      1969-06-17           english   1
2      1969-09-10            others   1
3      1969-09-23           english   1
4      1969-12-12           english   1
...           ...               ...  ..
2524   2068-04-02           english   1
2525   2068-06-12           english   1
2526   2068-07-18           english   1
2527   2068-10-10           english   1
2528   2068-11-06           english   1

[2529 rows x 3 columns]

In [ ]:
# .crosstab() -->
pd.crosstab(read_imdb_data.release_date,read_imdb_data.original_language ).reset_index()

original_language release_date  english  hindi  others
0                   1969-01-01        1      0       0
1                   1969-06-17        1      0       0
2                   1969-09-10        0      0       1
3                   1969-09-23        1      0       0
4                   1969-12-12        1      0       0
...                        ...      ...    ...     ...
2393                2068-04-02        1      0       0
2394                2068-06-12        1      0       0
2395                2068-07-18        1      0       0
2396                2068-10-10        1      0       0
2397                2068-11-06        1      0       0

[2398 rows x 4 columns]

In [ ]:
read_imdb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   datetime64[ns]
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(3), object(17)
memory usage: 539.2+ KB

In [ ]:
# .astype() --> Typecasting
# Int to str
read_imdb_data.id.astype('str').astype('int')

0          1
1          2
2          3
3          4
4          5
        ...
2995    2996
2996    2997
2997    2998
2998    2999
2999    3000
Name: id, Length: 3000, dtype: int64

In [ ]:
read_imdb_data['date_concat'] = read_imdb_data.release_date.dt.year.astype('str') + '-' + read_imdb_data.release_date.dt.month.astype('str')

In [ ]:
read_imdb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   datetime64[ns]
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
 23  date_concat            3000 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(3), object(18)
memory usage: 562.6+ KB

In [ ]:
read_imdb_data.date_concat[0]

'2015-2'

### Caching & Parallelization

In [ ]:
#  Parallelization & Caching

#####  Parallelization

In [ ]:
# Parallelization
!pip install pandarallel
from pandarallel import pandarallel

Collecting pandarallel
  Downloading pandarallel-1.6.5.tar.gz (14 kB)
  Preparing metadata (setup.py) ... done
Collecting dill>=0.3.1 (from pandarallel)
  Downloading dill-0.3.8-py3-none-any.whl (116 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 3.3 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1 in /usr/local/lib/python3.10/dist-packages (from pandarallel) (2.0.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from pandarallel) (5.9.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1->pandarallel) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1->pandarallel) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1->pandarallel) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas>=1->pandarallel) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1->pandarallel) (1.16.0)
Building wheels for collected packages: pandarallel
  Building wheel for pandarallel (setup.py) ... done
  Created wheel for pandarallel: filename=pandarallel-1.6.5-py3-none-any.whl size=16673 sha256=965f1d064002ecfea78fb7d4139444b5d6d4681187e0e5121098f4340fc1be89
  Stored in directory: /root/.cache/pip/wheels/50/4f/1e/34e057bb868842209f1623f195b74fd7eda229308a7352d47f
Successfully built pandarallel
Installing collected packages: dill, pandarallel
Successfully installed dill-0.3.8 pandarallel-1.6.5

In [ ]:
# pandarallel.initialize(nb_workers=1)

In [ ]:
# %time  --> 1 execution and time taken
# %timeit --> 1000 executions and avg time taken

In [ ]:
read_imdb_data = pd.concat([read_imdb_data]* 5)
read_imdb_data.shape

(15000, 23)

In [ ]:
# Column with all links.parallel_apply(funciton)

In [ ]:
pandarallel.initialize(nb_workers=1)
%time read_imdb_data.cast.parallel_apply(parse_json,key = 'name')

INFO: Pandarallel will run on 1 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
CPU times: user 527 ms, sys: 139 ms, total: 666 ms
Wall time: 1min 36s

0       Rob Corddry,Craig Robinson,Clark Duke,Adam Sco...
1       Anne Hathaway,Julie Andrews,H√©ctor Elizondo,J...
2       Miles Teller,J.K. Simmons,Melissa Benoist,Aust...
3       Vidya Balan,Nawazuddin Siddiqui,Parambrata Cha...
4       Kim Kang-woo,Jo Jae-hyeon,Park Si-yeon,Kim Joo...
                              ...
2995    Tom Berenger,William McNamara,–≠—Ä–∏–∫–∞ –≠–ª–...
2996    Mira Barkhammar,Mira Grosin,Liv LeMoyne,David ...
2997    Geena Davis,Samuel L. Jackson,Yvonne Zima,Crai...
2998    Ben Stiller,Jennifer Aniston,Philip Seymour Ho...
2999    Taylor Lautner,Lily Collins,Alfred Molina,Jaso...
Name: cast, Length: 15000, dtype: object

In [ ]:
pandarallel.initialize(nb_workers = 2)
%time read_imdb_data.cast.parallel_apply(parse_json,key = 'name')

INFO: Pandarallel will run on 2 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
CPU times: user 316 ms, sys: 138 ms, total: 455 ms
Wall time: 57.6 s

0       Rob Corddry,Craig Robinson,Clark Duke,Adam Sco...
1       Anne Hathaway,Julie Andrews,H√©ctor Elizondo,J...
2       Miles Teller,J.K. Simmons,Melissa Benoist,Aust...
3       Vidya Balan,Nawazuddin Siddiqui,Parambrata Cha...
4       Kim Kang-woo,Jo Jae-hyeon,Park Si-yeon,Kim Joo...
                              ...
2995    Tom Berenger,William McNamara,–≠—Ä–∏–∫–∞ –≠–ª–...
2996    Mira Barkhammar,Mira Grosin,Liv LeMoyne,David ...
2997    Geena Davis,Samuel L. Jackson,Yvonne Zima,Crai...
2998    Ben Stiller,Jennifer Aniston,Philip Seymour Ho...
2999    Taylor Lautner,Lily Collins,Alfred Molina,Jaso...
Name: cast, Length: 15000, dtype: object

In [ ]:
# pandarallel.initialize(nb_workers = 4)
# %time read_imdb_data.cast.parallel_apply(parse_json,key = 'name')

INFO: Pandarallel will run on 4 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
CPU times: user 60.6 ms, sys: 80.1 ms, total: 141 ms
Wall time: 5.86 s

0       Rob Corddry,Craig Robinson,Clark Duke,Adam Sco...
1       Anne Hathaway,Julie Andrews,H√©ctor Elizondo,J...
2       Miles Teller,J.K. Simmons,Melissa Benoist,Aust...
3       Vidya Balan,Nawazuddin Siddiqui,Parambrata Cha...
4       Kim Kang-woo,Jo Jae-hyeon,Park Si-yeon,Kim Joo...
                              ...
2995    Tom Berenger,William McNamara,–≠—Ä–∏–∫–∞ –≠–ª–...
2996    Mira Barkhammar,Mira Grosin,Liv LeMoyne,David ...
2997    Geena Davis,Samuel L. Jackson,Yvonne Zima,Crai...
2998    Ben Stiller,Jennifer Aniston,Philip Seymour Ho...
2999    Taylor Lautner,Lily Collins,Alfred Molina,Jaso...
Name: cast, Length: 3000, dtype: object

In [ ]:
%time read_imdb_data.cast.apply(parse_json,key = 'name')

CPU times: user 45.8 s, sys: 304 ms, total: 46.1 s
Wall time: 46.5 s

0       Rob Corddry,Craig Robinson,Clark Duke,Adam Sco...
1       Anne Hathaway,Julie Andrews,H√©ctor Elizondo,J...
2       Miles Teller,J.K. Simmons,Melissa Benoist,Aust...
3       Vidya Balan,Nawazuddin Siddiqui,Parambrata Cha...
4       Kim Kang-woo,Jo Jae-hyeon,Park Si-yeon,Kim Joo...
                              ...
2995    Tom Berenger,William McNamara,–≠—Ä–∏–∫–∞ –≠–ª–...
2996    Mira Barkhammar,Mira Grosin,Liv LeMoyne,David ...
2997    Geena Davis,Samuel L. Jackson,Yvonne Zima,Crai...
2998    Ben Stiller,Jennifer Aniston,Philip Seymour Ho...
2999    Taylor Lautner,Lily Collins,Alfred Molina,Jaso...
Name: cast, Length: 30000, dtype: object

##### Caching

In [ ]:
# joblib
from joblib import Memory
mem = Memory(location='cache')

In [ ]:
@mem.cache
def parse_json_cache(s,key):
  try:
    j= eval(s)
    return ','.join(list(pd.json_normalize(j)[key]))
  except:
    return s

In [ ]:
%time read_imdb_data.cast.apply(parse_json_cache,key = 'name') #First time run

Streaming output truncated to the last 5000 lines.
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 11, 'character': 'Caesar', 'credit_id': "
 "'52fe430ec3a36847f8037199', 'gender': 2, 'id': 7505, 'name': 'Roddy "
 "McDowall', 'order': 0, 'profile_path': '/e0OZn5SUXHghdmAgJbF3uLHD5gf.jpg'}, "
 "{'cast_id': 21, 'character': 'Lisa', 'credit_id': "
 "'52fe430ec3a36847f80371bf', 'gender': 1, 'id': 18648, 'name': 'Natalie "
 "Trundy', 'order': 1, 'profile_path': '/50ljrtCFeFQRFURoSgf1hrgdCPw.jpg'}, "
 "{'cast_id': 23, 'character': 'MacDonald', 'credit_id': "
 "'52fe430ec3a36847f80371c7', 'gender': 2, 'id': 103707, 'name': 'Austin "
 "Stoker', 'order': 2, 'profile_path': '/ukRtXDLGlmaSE4lAruhAqG7IsLJ.jpg'}, "
 "{'cast_id': 26, 'character': 'Kolp', 'credit_id': "
 "'52fe430ec3a3684..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 1, 'character': 'David Reed', 'credit_id': "
 "'52fe43da9251416c75020b77', 'gender': 2, 'id': 67685, 'name': 'Richard "
 "Carlson', 'order': 0, 'profile_path': '/dGBs79xPf6fFI9p0rEiasmn5G3X.jpg'}, "
 "{'cast_id': 2, 'character': 'Kay Lawrence', 'credit_id': "
 "'52fe43da9251416c75020b7b', 'gender': 1, 'id': 31169, 'name': 'Julie Adams', "
 "'order': 1, 'profile_path': '/p6abeZkETxG9h2JdaKwzyesWSFv.jpg'}, {'cast_id': "
 "3, 'character': 'Mark Williams', 'credit_id': '52fe43da9251416c75020b7f', "
 "'gender': 2, 'id': 54681, 'name': 'Richard Denning', 'order': 2, "
 "'profile_path': '/kGYesw34sQkfazqQj3Dy2Ul8lmx.jpg'}, {'cast_id': 4, "
 "'character': 'Carl Maia', 'credit_id': '52..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 3, 'character': 'Jack Moniker', 'credit_id': "
 "'52fe450ac3a368484e045017', 'gender': 2, 'id': 2157, 'name': 'Robin "
 "Williams', 'order': 0, 'profile_path': '/sojtJyIV3lkUeThD7A2oHNm8183.jpg'}, "
 "{'cast_id': 4, 'character': 'Governor Anthony Cloyden Hayes', 'credit_id': "
 '\'52fe450ac3a368484e04501b\', \'gender\': 2, \'id\': 11390, \'name\': "Peter '
 'O\'Toole", \'order\': 1, \'profile_path\': '
 "'/7esSG4iZHueb5Nh8RBBhtRZLpom.jpg'}, {'cast_id': 5, 'character': 'Barry "
 "Nye', 'credit_id': '52fe450ac3a368484e04501f', 'gender': 2, 'id': 8872, "
 "'name': 'Rick Moranis', 'order': 2, 'profile_path': "
 "'/rVZbTJjM4g0Um6trlLHRiBzBO7t.jpg'}, {'cast_id': 6, 'character': 'Ern..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 1, 'character': 'Adela Quested', 'credit_id': "
 "'52fe468b9251416c7507ba7b', 'gender': 1, 'id': 351, 'name': 'Judy Davis', "
 "'order': 0, 'profile_path': '/xQMA72T6yz6ebJXv1pCuZC1fDJo.jpg'}, {'cast_id': "
 "2, 'character': 'Prof. Godbole', 'credit_id': '52fe468b9251416c7507ba7f', "
 "'gender': 2, 'id': 12248, 'name': 'Alec Guinness', 'order': 1, "
 "'profile_path': '/nv3ppxgUQJytFGXZNde4f9ZlshB.jpg'}, {'cast_id': 3, "
 "'character': 'Mrs. Moore', 'credit_id': '52fe468b9251416c7507ba83', "
 "'gender': 1, 'id': 3672, 'name': 'Peggy Ashcroft', 'order': 2, "
 "'profile_path': '/xFJWz7XbWTwkhaAnV29yCUsTc9o.jpg'}, {'cast_id': 4, "
 "'character': 'Richard Fielding', 'credit_id': '52fe468b9251416c7507ba87', "
 "'gender': 2, 'id': 1292, 'name': 'James Fox', 'order': 3, 'profile_path': "
 "'/hhWJskOI5sM8gikgJTQJZidkGRb.jpg'}, {'cast_id': 5, 'character': 'Dr. Aziz "
 "H. Ahmed', 'credit_id': '52fe468b9251416c7507ba8b', 'gender': 2, 'id': "
 "78951, 'name': 'Victor Banerjee', 'order': 4, 'profile_path': "
 "'/s19NsocK35S7RFs1vuS61tK3dET.jpg'}, {'cast_id': 6, 'character': 'Ronny "
 "Heaslop', 'credit_id': '52fe468b9251416c7507ba8f', 'gender': 2, 'id': 53517, "
 "'name': 'Nigel Havers', 'order': 5, 'profile_path': "
 "'/hZNkoh83CUAlOmqMwAz7i1jwWgi.jpg'}, {'cast_id': 7, 'character': 'Maj. "
 "McBryde', 'credit_id': '52fe468b9251416c7507ba93', 'gender': 2, 'id': 47520, "
 "'name': 'Michael Culver', 'order': 6, 'profile_path': "
 "'/njBI1pTMMMlon5LufetA1vHn819.jpg'}]"), key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 11, 'character': 'John Finnegan', 'credit_id': "
 "'52fe44fac3a36847f80b54f1', 'gender': 2, 'id': 4515, 'name': 'Treat "
 "Williams', 'order': 0, 'profile_path': '/uKejRJTEVOy6IOsJX2mJH3SwbTl.jpg'}, "
 "{'cast_id': 12, 'character': 'Trillian St. James', 'credit_id': "
 "'52fe44fac3a36847f80b54f5', 'gender': 1, 'id': 10696, 'name': 'Famke "
 "Janssen', 'order': 1, 'profile_path': '/9wHWq6Mnfpn8L1diMxjr26ReZWl.jpg'}, "
 "{'cast_id': 13, 'character': 'Simon Canton', 'credit_id': "
 "'52fe44fac3a36847f80b54f9', 'gender': 2, 'id': 16293, 'name': 'Anthony "
 "Heald', 'order': 2, 'profile_path': '/nRXLwMuuv5nUbEz2sFLtEU4zUYg.jpg'}, "
 "{'cast_id': 14, 'character': 'Joey Pantucci', 'c..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 1, 'character': 'Thomas Barnes', 'credit_id': "
 "'52fe447fc3a36847f8099a33', 'gender': 2, 'id': 6065, 'name': 'Dennis Quaid', "
 "'order': 0, 'profile_path': '/fSnnQg8y1LB9yHbn2WuEcUb8i9Y.jpg'}, {'cast_id': "
 "2, 'character': 'Kent Taylor', 'credit_id': '52fe447fc3a36847f8099a37', "
 "'gender': 2, 'id': 28657, 'name': 'Matthew Fox', 'order': 1, 'profile_path': "
 "'/sDwybT6aujgEQhesfg8Mt14dgsN.jpg'}, {'cast_id': 3, 'character': 'Howard "
 "Lewis', 'credit_id': '52fe447fc3a36847f8099a3b', 'gender': 2, 'id': 2178, "
 "'name': 'Forest Whitaker', 'order': 2, 'profile_path': "
 "'/4pMQkelS5lK661m9Kz3oIxLYiyS.jpg'}, {'cast_id': 4, 'character': 'Rex "
 "Brooks', 'credit_id': '52fe4..., key='name')
_________________________________________________parse_json_cache - 0.1s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 1, 'character': 'Dorothy', 'credit_id': "
 "'52fe44b2c3a368484e031a33', 'gender': 1, 'id': 32715, 'name': 'Diana Ross', "
 "'order': 0, 'profile_path': '/6xVBaLk6mBeneEQSJchsQ276FTX.jpg'}, {'cast_id': "
 "2, 'character': 'Scarecrow', 'credit_id': '52fe44b2c3a368484e031a37', "
 "'gender': 2, 'id': 82702, 'name': 'Michael Jackson', 'order': 1, "
 "'profile_path': '/9nDsffd8kZ2O9MlnIiqWRVausM7.jpg'}, {'cast_id': 3, "
 "'character': 'Tinman', 'credit_id': '52fe44b2c3a368484e031a3b', 'gender': 2, "
 "'id': 92899, 'name': 'Nipsey Russell', 'order': 2, 'profile_path': "
 "'/hKPKPD7opWURQXLa302t3kslarh.jpg'}, {'cast_id': 4, 'character': 'Lion / "
 "Fleetwood Coup de Ville', 'credit_id..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(('[{\'cast_id\': 1, \'character\': "Michael \'Mike\' Brody", \'credit_id\': '
 "'52fe47409251416c75092e41', 'gender': 2, 'id': 6065, 'name': 'Dennis Quaid', "
 "'order': 0, 'profile_path': '/fSnnQg8y1LB9yHbn2WuEcUb8i9Y.jpg'}, {'cast_id': "
 "2, 'character': 'Kathryn Morgan', 'credit_id': '52fe47419251416c75092e45', "
 "'gender': 1, 'id': 29710, 'name': 'Bess Armstrong', 'order': 1, "
 "'profile_path': '/fH9l0jd9uYFPlW8iHKFyQnL3ThW.jpg'}, {'cast_id': 3, "
 "'character': 'Philip FitzRoyce', 'credit_id': '52fe47419251416c75092e49', "
 "'gender': 2, 'id': 24743, 'name': 'Simon MacCorkindale', 'order': 2, "
 "'profile_path': '/pss165HPDGUf6BfPAqNzB0oOf75.jpg'}, {'cast_id': 4, "
 "'character': 'Ca..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 10, 'character': 'Dracula', 'credit_id': "
 "'52fe438b9251416c7501484d', 'gender': 2, 'id': 17276, 'name': 'Gerard "
 "Butler', 'order': 0, 'profile_path': '/i54XoxYieuff2w6MwyfwVUBvmR0.jpg'}, "
 "{'cast_id': 11, 'character': 'Matthew Van Helsing', 'credit_id': "
 "'52fe438b9251416c75014851', 'gender': 2, 'id': 290, 'name': 'Christopher "
 "Plummer', 'order': 1, 'profile_path': '/fauMGxa6dc86nHNenQ8X6DlE6YV.jpg'}, "
 "{'cast_id': 12, 'character': 'Simon Sheppard', 'credit_id': "
 "'52fe438b9251416c75014855', 'gender': 2, 'id': 9012, 'name': 'Jonny Lee "
 "Miller', 'order': 2, 'profile_path': '/70oZd4dPWNAibagHJvRU1Tf9e6h.jpg'}, "
 "{'cast_id': 13, 'character': 'Mary Heller', '..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 8, 'character': 'Officer Gunther Toody', 'credit_id': "
 "'53b9f74ec3a3685eb70061a9', 'gender': 2, 'id': 57116, 'name': 'David "
 "Johansen', 'order': 0, 'profile_path': '/hQq0pmBBcmapA8YPxsgnDuZnEAa.jpg'}, "
 "{'cast_id': 1, 'character': 'Officer Francis Muldoon', 'credit_id': "
 "'52fe447a9251416c91012149', 'gender': 2, 'id': 11885, 'name': 'John C. "
 "McGinley', 'order': 1, 'profile_path': '/6AJL0ylRtJ9vcR57yEenhWHXHFt.jpg'}, "
 "{'cast_id': 2, 'character': 'Velma Velour', 'credit_id': "
 "'52fe447a9251416c9101214d', 'gender': 1, 'id': 53122, 'name': 'Fran "
 "Drescher', 'order': 2, 'profile_path': '/vQxr8CRgyDkH3GTFLwacs9W9tF4.jpg'}, "
 "{'cast_id': 9, 'character': 'Polic..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 1, 'character': 'Sheriff Bryce Hammond', 'credit_id': "
 "'52fe4535c3a36847f80c2271', 'gender': 2, 'id': 880, 'name': 'Ben Affleck', "
 "'order': 0, 'profile_path': '/cPuPt6mYJ83DjvO3hbjNGug6Fbi.jpg'}, {'cast_id': "
 "2, 'character': 'Dr. Timothy Flyte', 'credit_id': "
 '\'52fe4535c3a36847f80c2275\', \'gender\': 2, \'id\': 11390, \'name\': "Peter '
 'O\'Toole", \'order\': 1, \'profile_path\': '
 "'/7esSG4iZHueb5Nh8RBBhtRZLpom.jpg'}, {'cast_id': 3, 'character': 'Lisa "
 "Pailey', 'credit_id': '52fe4535c3a36847f80c2279', 'gender': 1, 'id': 16850, "
 "'name': 'Rose McGowan', 'order': 2, 'profile_path': "
 "'/llI2Fc6G0wqZlASpIEGWnLViZxD.jpg'}, {'cast_id': 4, 'character': 'Jennifer..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 2, 'character': '', 'credit_id': '53306374c3a3685fac006bd3', "
 "'gender': 2, 'id': 26457, 'name': 'Matthew Lillard', 'order': 1, "
 "'profile_path': '/gJsQkX20g0ABquHqVpBJzMXR2JF.jpg'}, {'cast_id': 3, "
 "'character': '', 'credit_id': '5330637bc3a3685fc3006df7', 'gender': 1, 'id': "
 "17832, 'name': 'Carla Gugino', 'order': 2, 'profile_path': "
 "'/xddYLCp8zWLgYcQRck7REEgCUWl.jpg'}, {'cast_id': 4, 'character': 'Tobi', "
 "'credit_id': '53306388c3a3685fe2006dec', 'gender': 2, 'id': 2387, 'name': "
 "'Patrick Stewart', 'order': 3, 'profile_path': "
 "'/wEy5qSDT5jT3ZASc2hbwi59voPL.jpg'}, {'cast_id': 11, 'character': 'Cabbie', "
 "'credit_id': '53fed2c60e0a2658280002b7', 'gender': 0, 'id': 20632, 'name': "
 "'Maduka Steady', 'order': 4, 'profile_path': None}]"), key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 13, 'character': 'R', 'credit_id': '52fe48649251416c9108ad65', "
 "'gender': 2, 'id': 3292, 'name': 'Nicholas Hoult', 'order': 0, "
 "'profile_path': '/27NbnWKzco1CCDHtR2AVVab8Dli.jpg'}, {'cast_id': 11, "
 "'character': 'Julie Grigio', 'credit_id': '52fe48649251416c9108ad5d', "
 "'gender': 1, 'id': 20374, 'name': 'Teresa Palmer', 'order': 1, "
 "'profile_path': '/v9t3baWMoUcdEhec5SkCwa1aiL6.jpg'}, {'cast_id': 12, "
 "'character': 'Nora Greene', 'credit_id': '52fe48649251416c9108ad61', "
 "'gender': 1, 'id': 124644, 'name': 'Analeigh Tipton', 'order': 2, "
 "'profile_path': '/oFTEyLJykoAWtUOT9RPKco3F1FJ.jpg'}, {'cast_id': 16, "
 "'character': 'M / Marcus', 'credit_id': '52fe486..., key='name')
_________________________________________________parse_json_cache - 0.1s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 1, 'character': 'James', 'credit_id': "
 "'52fe45e89251416c750669e5', 'gender': 2, 'id': 6408, 'name': 'Nick Stahl', "
 "'order': 0, 'profile_path': '/3IBXRFxLdpk3PrN6ypdiWZi6xe3.jpg'}, {'cast_id': "
 "2, 'character': 'Tara', 'credit_id': '52fe45e89251416c750669e9', 'gender': "
 "1, 'id': 1285, 'name': 'AnnaSophia Robb', 'order': 1, 'profile_path': "
 "'/jktnEA6LUBl4JTh7uPRfUFQFXBn.jpg'}, {'cast_id': 3, 'character': 'Joleen', "
 "'credit_id': '52fe45e89251416c750669ed', 'gender': 1, 'id': 6885, 'name': "
 "'Charlize Theron', 'order': 2, 'profile_path': "
 "'/aHOB9UMgSI7MlXF3GMZaVQXqfQg.jpg'}, {'cast_id': 4, 'character': 'Randall', "
 "'credit_id': '52fe45e99251416c750669f1', 'gender': 2, 'id': 57755, 'name': "
 "'Woody Harrelson', 'order': 3, 'profile_path': "
 "'/1ecdooAHICUhCZKKEKlFtccEmTU.jpg'}, {'cast_id': 5, 'character': 'Mr. "
 "Reedy', 'credit_id': '52fe45e99251416c750669f5', 'gender': 2, 'id': 2778, "
 "'name': 'Dennis Hopper', 'order': 4, 'profile_path': "
 "'/56nj2DfMVU3F9qUagZWMePLbrKF.jpg'}]"), key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 1, 'character': 'James Averill', 'credit_id': "
 "'52fe43d49251416c7501fcaf', 'gender': 2, 'id': 10823, 'name': 'Kris "
 "Kristofferson', 'order': 0, 'profile_path': "
 "'/hiGkNoiAwnUgY9XZ3YhiWMvKngi.jpg'}, {'cast_id': 2, 'character': 'Nathan D. "
 "Champion', 'credit_id': '52fe43d49251416c7501fcb3', 'gender': 2, 'id': 4690, "
 "'name': 'Christopher Walken', 'order': 1, 'profile_path': "
 "'/ysO1GwRzLT9OVAB9Y2SKHxomqDr.jpg'}, {'cast_id': 3, 'character': 'Billy "
 "Irvine', 'credit_id': '52fe43d49251416c7501fcb7', 'gender': 2, 'id': 5049, "
 "'name': 'John Hurt', 'order': 2, 'profile_path': "
 "'/tW6cOElGBdJl8nNrHwL6gvxvdkI.jpg'}, {'cast_id': 4, 'character': 'Ella "
 "Watson', ..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 10, 'character': 'Father', 'credit_id': "
 "'5923bdacc3a3680426006fde', 'gender': 0, 'id': 1497778, 'name': 'Emmanuel "
 "Garijo', 'order': 1, 'profile_path': '/cDqKqZg1Fek2neLDoQOQYoQNWhP.jpg'}, "
 "{'cast_id': 11, 'character': 'Young Adult Son', 'credit_id': "
 "'5923bdbac3a3680426006feb', 'gender': 2, 'id': 1327993, 'name': 'Tom "
 "Hudson', 'order': 2, 'profile_path': '/dRekOwP7mrImBB8XAhppzPLNp8R.jpg'}, "
 "{'cast_id': 12, 'character': 'Child Son', 'credit_id': "
 "'5923bdc3c3a3680474006504', 'gender': 0, 'id': 1822014, 'name': 'Baptiste "
 "Goy', 'order': 3, 'profile_path': None}, {'cast_id': 13, 'character': "
 "'Baby', 'credit_id': '5923bdcac3a36804a300670a', 'gender': 0, 'id': 1822015, "
 "'name': 'Axel Devillers', 'order': 4, 'profile_path': None}, {'cast_id': 14, "
 "'character': 'Mother', 'credit_id': '5923bdd5925141055e007cac', 'gender': 0, "
 "'id': 1515111, 'name': 'Barbara Beretta', 'order': 5, 'profile_path': None}]"), key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 20, 'character': 'Archy', 'credit_id': "
 "'52fe45a49251416c7505d67b', 'gender': 2, 'id': 2983, 'name': 'Mark Strong', "
 "'order': 0, 'profile_path': '/tr8nXYhY1ZWGmsXuHFHk6MBeL9Q.jpg'}, {'cast_id': "
 "10, 'character': 'Lenny Cole', 'credit_id': '52fe45a49251416c7505d65b', "
 "'gender': 2, 'id': 207, 'name': 'Tom Wilkinson', 'order': 1, 'profile_path': "
 "'/4mxZKgdem0sQ8hJd0Y7TREwq7TJ.jpg'}, {'cast_id': 6, 'character': 'Johnny "
 "Quid', 'credit_id': '52fe45a49251416c7505d64b', 'gender': 2, 'id': 20286, "
 "'name': 'Toby Kebbell', 'order': 2, 'profile_path': "
 "'/wQU3uFk2TWjT2qfs2Z6rkdbWbjx.jpg'}, {'cast_id': 5, 'character': 'One-Two', "
 "'credit_id': '52fe45a49251416c750..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 18, 'character': 'Liu Jian', 'credit_id': "
 "'52fe433ac3a36847f8043f37', 'gender': 2, 'id': 1336, 'name': 'Jet Li', "
 "'order': 0, 'profile_path': '/5himGJzSuLoHwqacTz7sXWqgeMt.jpg'}, {'cast_id': "
 "19, 'character': 'Jessica Kamen', 'credit_id': '52fe433ac3a36847f8043f3b', "
 "'gender': 1, 'id': 2233, 'name': 'Bridget Fonda', 'order': 1, "
 "'profile_path': '/yWxhdN59eksIqyBHdjUcLRgCIaI.jpg'}, {'cast_id': 20, "
 "'character': 'Insp. Richard', 'credit_id': '52fe433ac3a36847f8043f3f', "
 "'gender': 2, 'id': 10698, 'name': 'Tch√©ky Karyo', 'order': 2, "
 "'profile_path': '/9rMF25F5r3Giix9jkwfuUz2utHv.jpg'}, {'cast_id': 21, "
 "'character': 'Lupo', 'credit_id': '52fe433ac3a3684..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 1002, 'character': 'Terri', 'credit_id': "

/usr/local/lib/python3.10/dist-packages/joblib/memory.py:577: UserWarning: Persisting input arguments took 0.64s to run.If this happens often in your code, it can cause performance problems (results will be correct in all cases). The reason for this is probably some large input arguments for a wrapped function.
  return self._cached_call(args, kwargs, shelving=False)[0]

Streaming output truncated to the last 5000 lines.
parse_json_cache(("[{'cast_id': 1, 'character': 'Blaire Lilly', 'credit_id': "
 "'53d8e6ec0e0a261c840023c5', 'gender': 1, 'id': 444211, 'name': 'Shelley "
 "Hennig', 'order': 0, 'profile_path': '/7o9Cw2YO63zsQBlFkdbKn3YcUvQ.jpg'}, "
 "{'cast_id': 17, 'character': 'Mitch Roussel', 'credit_id': "
 "'5464324ac3a36804b4000b8b', 'gender': 0, 'id': 1385058, 'name': 'Moses Jacob "
 "Storm', 'order': 1, 'profile_path': '/mFnBuVTT6CjQ4GYAOJpsSeBN8KS.jpg'}, "
 '{\'cast_id\': 2, \'character\': \'Jessica "Jess" Felton\', \'credit_id\': '
 "'53d8e6f60e0a261c7e0024b2', 'gender': 1, 'id': 155621, 'name': 'Renee "
 "Olstead', 'order': 2, 'profile_path': '/Alru3bM9sSE0Q6yeN5fLwNxIy8v.jpg'}, "
 "{'cast_id': 14, 'character': '..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 3, 'character': 'Otilia', 'credit_id': "
 "'52fe432bc3a36847f803fb75', 'gender': 1, 'id': 20699, 'name': 'Anamaria "
 "Marinca', 'order': 0, 'profile_path': '/ajLN2RMuYHgTEFAzs8x8vZH0Rlu.jpg'}, "
 "{'cast_id': 2, 'character': 'Gabita', 'credit_id': "
 "'52fe432bc3a36847f803fb71', 'gender': 1, 'id': 20698, 'name': 'Laura "
 "Vasiliu', 'order': 1, 'profile_path': '/fMTklQIBMEPtwKwiYJRTKa9Sd9B.jpg'}, "
 '{\'cast_id\': 6, \'character\': "Domnu\' Bebe", \'credit_id\': '
 "'52fe432bc3a36847f803fb85', 'gender': 2, 'id': 39959, 'name': 'Vlad Ivanov', "
 "'order': 2, 'profile_path': '/zZn7WAHQeignC0WPfhA5d0SNqjZ.jpg'}, {'cast_id': "
 "7, 'character': 'Adi', 'credit_id': '52fe432bc3a368..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 2, 'character': 'Chance', 'credit_id': "
 "'52fe44b6c3a368484e032a63', 'gender': 2, 'id': 521, 'name': 'Michael J. "
 "Fox', 'order': 0, 'profile_path': '/aeN1cA04vVXKrVy1SuS1JOhABBs.jpg'}, "
 "{'cast_id': 3, 'character': 'Sassy', 'credit_id': "
 "'52fe44b6c3a368484e032a67', 'gender': 1, 'id': 35, 'name': 'Sally Field', "
 "'order': 1, 'profile_path': '/ymhpsxujOO3a9qaGYSpkenCt9Le.jpg'}, {'cast_id': "
 "1, 'character': 'Shadow', 'credit_id': '52fe44b6c3a368484e032a5f', 'gender': "
 "2, 'id': 8853, 'name': 'Ralph Waite', 'order': 2, 'profile_path': "
 "'/fvLzvzgEhznLngnM628rXTt53AX.jpg'}, {'cast_id': 5, 'character': 'Bob "
 "Seaver', 'credit_id': '52fe44b6c3a368484e032a6b', 'ge..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 24, 'character': 'Malcolm Adekanbi', 'credit_id': "
 "'561a3f019251412c9c000845', 'gender': 0, 'id': 587506, 'name': 'Shameik "
 "Moore', 'order': 0, 'profile_path': '/1BpRfV7Ip53O5WNXwftgsbmnQ7x.jpg'}, "
 '{\'cast_id\': 6, \'character\': "Cassandra \'Diggy\' Andrews", '
 "'credit_id': '5482839fc3a36817a5007a41', 'gender': 1, 'id': 1253355, 'name': "
 "'Kiersey Clemons', 'order': 1, 'profile_path': "
 "'/sOXELJHizB1cK0OzWRubGGg4l8S.jpg'}, {'cast_id': 4, 'character': "
 '"James \'Jib\' Caldones", \'credit_id\': \'54828387c3a36829ae006f08\', '
 "'gender': 2, 'id': 1291350, 'name': 'Tony Revolori', 'order': 2, "
 "'profile_path': '/gZbodAVh4dv06zc4zmAnyBdCkah.jpg'}, {'cast_id': 0..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 1, 'character': 'Dr. Henry Goose / Hotel Manager / Isaac Sachs "
 "/ Dermot Hoggins / Cavendish Look-a-Like Actor / Zachry', 'credit_id': "
 "'52fe48a89251416c91094135', 'gender': 2, 'id': 31, 'name': 'Tom Hanks', "
 "'order': 0, 'profile_path': '/pQFoyx7rp09CJTAb932F2g8Nlho.jpg'}, {'cast_id': "
 "2, 'character': 'Native Woman / Jocasta Ayrs / Luisa Rey / Indian Party "
 "Guest / Ovid / Meronym', 'credit_id': '52fe48a89251416c91094139', 'gender': "
 "1, 'id': 4587, 'name': 'Halle Berry', 'order': 1, 'profile_path': "
 "'/AmCXHowNbUXpNf41dNrxNB0naM2.jpg'}, {'cast_id': 7, 'character': 'Captain "
 "Molyneux / Vyvyan Ayrs / Timothy Cavendish / Korean Musician / Prescient 2', "
 "'..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 13, 'character': 'Robby Gallagher', 'credit_id': "
 "'52fe44c2c3a36847f80a8605', 'gender': 2, 'id': 5576, 'name': 'Val Kilmer', "
 "'order': 0, 'profile_path': '/AlhPeiH8R4reMNGNQ9ag1FPbuW9.jpg'}, {'cast_id': "
 "14, 'character': 'Cmdr. Kate Bowman', 'credit_id': "
 "'52fe44c2c3a36847f80a8609', 'gender': 1, 'id': 530, 'name': 'Carrie-Anne "
 "Moss', 'order': 1, 'profile_path': '/pgyBbrapYBoGvg5M3OIvVQ5Ne7m.jpg'}, "
 "{'cast_id': 15, 'character': 'Lt. Ted Santen', 'credit_id': "
 "'52fe44c2c3a36847f80a860d', 'gender': 2, 'id': 4589, 'name': 'Benjamin "
 "Bratt', 'order': 2, 'profile_path': '/nTJQPpn8OBkFM31rukjxM32rA0F.jpg'}, "
 "{'cast_id': 16, 'character': 'Dr. Quinn Burchena..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 1, 'character': 'Laurie Strode', 'credit_id': "
 "'52fe44409251416c7502e133', 'gender': 1, 'id': 8944, 'name': 'Jamie Lee "
 "Curtis', 'order': 0, 'profile_path': '/c4poMDwQ0nUj81m4WPriiv96ExZ.jpg'}, "
 "{'cast_id': 2, 'character': 'Michael Myers', 'credit_id': "
 "'52fe44409251416c7502e137', 'gender': 2, 'id': 69614, 'name': 'Brad Loree', "
 "'order': 1, 'profile_path': '/f308kzo6sRjHxIm2Ndbl2rfOVTn.jpg'}, {'cast_id': "
 "3, 'character': 'Freddie Harris', 'credit_id': '52fe44409251416c7502e13b', "
 "'gender': 2, 'id': 6485, 'name': 'Busta Rhymes', 'order': 2, 'profile_path': "
 "'/8rpV2yUeLmM9VGg3ZPgvx87gPrQ.jpg'}, {'cast_id': 4, 'character': 'Sara "
 "Moyer', 'credit_id': '5..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 1, 'character': 'San Lung', 'credit_id': "
 "'52fe46219251416c9104a3a7', 'gender': 2, 'id': 1336, 'name': 'Jet Li', "
 "'order': 0, 'profile_path': '/5himGJzSuLoHwqacTz7sXWqgeMt.jpg'}, {'cast_id': "
 "4, 'character': 'San Feng', 'credit_id': '52fe46219251416c9104a3b5', "
 "'gender': 0, 'id': 134662, 'name': 'Wong Chau-Yin ', 'order': 1, "
 "'profile_path': None}, {'cast_id': 7, 'character': 'Tin Lung / Er Long', "
 "'credit_id': '53c8b53fc3a3686e91000977', 'gender': 0, 'id': 1059241, 'name': "
 "'Yue Hoi', 'order': 2, 'profile_path': '/q1hOfFpXVuHlzJsWJVd1d6hjrVF.jpg'}, "
 "{'cast_id': 8, 'character': 'Pao Sheng-Feng / Wu Tang Dad', 'credit_id': "
 "'53c8b554c3a3686e79000998', 'gender': 0, 'id': 64707, 'name': 'Yu "
 "Cheng-Hui', 'order': 3, 'profile_path': '/l8kTAeeYuaP4AKZrrs6EJqgzCPy.jpg'}, "
 "{'cast_id': 9, 'character': 'Yee Feng / Er Feng', 'credit_id': "
 "'53c8b569c3a3686e82000989', 'gender': 0, 'id': 1342843, 'name': 'Ding Laam', "
 "'order': 4, 'profile_path': None}, {'cast_id': 10, 'character': 'One-eyed "
 "bandit', 'credit_id': '53c8b575c3a3686e76000903', 'gender': 0, 'id': 556698, "
 "'name': 'Ji Chun-Hua', 'order': 5, 'profile_path': "
 "'/5B6Y2LUHgw3SbDCwU2bljgv9xyH.jpg'}, {'cast_id': 11, 'character': 'Yee "
 "Lung', 'credit_id': '53c8b580c3a3686e7c000924', 'gender': 0, 'id': 1342844, "
 "'name': 'Woo Gin-Keung', 'order': 6, 'profile_path': None}]"), key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 1001, 'character': 'Det. Russell Logan', 'credit_id': "
 "'52fe45c5c3a36847f80d977f', 'gender': 2, 'id': 38560, 'name': 'Lou Diamond "
 "Phillips', 'order': 0, 'profile_path': '/afXcQRss7rZ6Ocx7PUQFbz7tPOm.jpg'}, "
 "{'cast_id': 1002, 'character': 'Tess Seaton', 'credit_id': "
 "'52fe45c5c3a36847f80d9783', 'gender': 0, 'id': 216171, 'name': 'Tracy "
 "Griffith', 'order': 1, 'profile_path': '/79HFuQ9nXKoJspsl2p9N0VohNxs.jpg'}, "
 "{'cast_id': 1003, 'character': 'Patrick Channing', 'credit_id': "
 "'52fe45c5c3a36847f80d9787', 'gender': 2, 'id': 54865, 'name': 'Jeff Kober', "
 "'order': 2, 'profile_path': '/txzJcwIFZKuGV7dBuGYKRqxfAuB.jpg'}, {'cast_id': "
 "1004, 'character': 'De..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 1, 'character': 'Michael', 'credit_id': "
 "'52fe4454c3a368484e01cf65', 'gender': 2, 'id': 6162, 'name': 'Paul Bettany', "
 "'order': 0, 'profile_path': '/xN2pJ3DIPacYviSSwDovxizPS2w.jpg'}, {'cast_id': "
 "2, 'character': 'Bob Hanson', 'credit_id': '52fe4454c3a368484e01cf69', "
 "'gender': 2, 'id': 6065, 'name': 'Dennis Quaid', 'order': 1, 'profile_path': "
 "'/fSnnQg8y1LB9yHbn2WuEcUb8i9Y.jpg'}, {'cast_id': 5, 'character': 'Gabriel', "
 "'credit_id': '52fe4454c3a368484e01cf75', 'gender': 2, 'id': 79072, 'name': "
 "'Kevin Durand', 'order': 2, 'profile_path': "
 "'/8hd4SCYe27yDBFjndoW2zMBKrYj.jpg'}, {'cast_id': 6, 'character': 'Sandra "
 "Anderson', 'credit_id': '52fe4454c3a368..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 12, 'character': 'Billy', 'credit_id': "
 "'52fe4de8c3a368484e204339', 'gender': 2, 'id': 1170994, 'name': 'Steven "
 "Nelson', 'order': 0, 'profile_path': '/rOqqTmuCK8HOPvK9m2HKiMZlTNV.jpg'}, "
 "{'cast_id': 13, 'character': 'Gloria', 'credit_id': "
 "'52fe4de8c3a368484e20433d', 'gender': 1, 'id': 102898, 'name': 'Honey "
 "Lauren', 'order': 1, 'profile_path': '/3KX0BJxr2hK4HsuqpiNa3HMNvOh.jpg'}, "
 "{'cast_id': 15, 'character': 'Paper Boy', 'credit_id': "
 "'52fe4de8c3a368484e204341', 'gender': 0, 'id': 1199462, 'name': 'Michael "
 "Mangiamele', 'order': 2, 'profile_path': None}, {'cast_id': 16, 'character': "
 "'Freddy Fishnets', 'credit_id': '52fe4de8c3a368484e204345', 'ge..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 6, 'character': 'Schmidt', 'credit_id': "
 "'52fe4d0e9251416c7512e751', 'gender': 2, 'id': 21007, 'name': 'Jonah Hill', "
 "'order': 0, 'profile_path': '/7GXzpyHLCEA36J9biB0wJVAauiO.jpg'}, {'cast_id': "
 "7, 'character': 'Jenko', 'credit_id': '52fe4d0e9251416c7512e755', 'gender': "
 "2, 'id': 38673, 'name': 'Channing Tatum', 'order': 1, 'profile_path': "
 "'/5L7BSYbzM8iizvIrS8EaaZoDrI3.jpg'}, {'cast_id': 9, 'character': 'Eric "
 "Molson', 'credit_id': '531f60cf92514177ae009196', 'gender': 2, 'id': 54697, "
 "'name': 'Dave Franco', 'order': 2, 'profile_path': "
 "'/po5nidw70UdgJc167Br5WYNysFU.jpg'}, {'cast_id': 8, 'character': 'Captain "
 "Dickson', 'credit_id': '52fe4d0e925141..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 4, 'character': 'Nick Brannen', 'credit_id': "
 "'52fe468fc3a36847f81059b5', 'gender': 2, 'id': 32895, 'name': 'Kevin James', "
 "'order': 1, 'profile_path': '/bve9CJ1xHvyyHSH4LsasG0eEQaW.jpg'}, {'cast_id': "
 "5, 'character': 'Ronny Valentine', 'credit_id': '52fe468fc3a36847f81059b9', "
 "'gender': 2, 'id': 4937, 'name': 'Vince Vaughn', 'order': 1, 'profile_path': "
 "'/r6ISnWjO5fA9QA1BTWUGaqdPyxE.jpg'}, {'cast_id': 3, 'character': 'Geneva "
 "Brannen', 'credit_id': '52fe468fc3a36847f81059b1', 'gender': 1, 'id': 1920, "
 "'name': 'Winona Ryder', 'order': 2, 'profile_path': "
 "'/gUyEOZpZlGBUkUxCxyoLEc9WejR.jpg'}, {'cast_id': 17, 'character': 'Beth', "
 "'credit_id': '52fe468f..., key='name')
_________________________________________________parse_json_cache - 0.1s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 0, 'character': 'Andre', 'credit_id': "
 "'53d7fceb0e0a2603470025c3', 'gender': 2, 'id': 2632, 'name': 'Chris Rock', "
 "'order': 0, 'profile_path': '/5JCYKerIL0SdiqygtLUpG9Sw37P.jpg'}, {'cast_id': "
 "1, 'character': 'Chelsea Brown', 'credit_id': '53d7fcfc0e0a2603470025c9', "
 "'gender': 1, 'id': 5916, 'name': 'Rosario Dawson', 'order': 1, "
 "'profile_path': '/dEK1rMmSJAPGdc2t1XWdbqBmvEq.jpg'}, {'cast_id': 13, "
 "'character': 'Silk', 'credit_id': '546426f7c3a36804c5000a8a', 'gender': 2, "
 "'id': 65920, 'name': 'J.B. Smoove', 'order': 2, 'profile_path': "
 "'/aT4Cw7HTDvdnMcJmTuW4BQqLI3x.jpg'}, {'cast_id': 3, 'character': 'Erica "
 "Long', 'credit_id': '53d7fd150e0a260340002..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 1, 'character': 'Tom McHugh', 'credit_id': "
 "'52fe484fc3a36847f8160def', 'gender': 2, 'id': 569, 'name': 'Ethan Hawke', "
 "'order': 0, 'profile_path': '/kcby6VYk6Gb0036nUyh8chY5ZAJ.jpg'}, {'cast_id': "
 "2, 'character': 'Geena Matthews', 'credit_id': '52fe484fc3a36847f8160df3', "
 "'gender': 1, 'id': 10399, 'name': 'Teri Polo', 'order': 1, 'profile_path': "
 "'/67k0q1YYVIeMd0wZalfqJ2FYLuu.jpg'}, {'cast_id': 3, 'character': 'Craig "
 "McHugh', 'credit_id': '52fe484fc3a36847f8160df7', 'gender': 2, 'id': 27238, "
 "'name': 'Brian McNamara', 'order': 2, 'profile_path': "
 "'/aemVY13WmPKj3TOWSvtbWs7Vgzu.jpg'}, {'cast_id': 4, 'character': 'Dwight', "
 "'credit_id': '52fe484fc3a36..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 4, 'character': 'Jen Kornfeldt', 'credit_id': "
 "'52fe46719251416c91054a15', 'gender': 1, 'id': 25541, 'name': 'Katherine "
 "Heigl', 'order': 0, 'profile_path': '/jOHVi7v3lvohI6KY7adnioiX5yl.jpg'}, "
 "{'cast_id': 5, 'character': 'Spencer Aimes', 'credit_id': "
 "'52fe46719251416c91054a19', 'gender': 2, 'id': 18976, 'name': 'Ashton "
 "Kutcher', 'order': 1, 'profile_path': '/cGEvhWHlJmSrYfkpfCtfZVeRVsP.jpg'}, "
 "{'cast_id': 6, 'character': 'Mr. Kornfeldt', 'credit_id': "
 "'52fe46719251416c91054a1d', 'gender': 2, 'id': 15112, 'name': 'Tom Selleck', "
 "'order': 2, 'profile_path': '/jCnmP0qYpCwWdVlZM4j9VNugmTj.jpg'}, {'cast_id': "
 "7, 'character': 'Mrs. Kornfeldt', 'credit_..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 1, 'character': 'Nim Rusoe', 'credit_id': "
 "'52fe43799251416c75011cad', 'gender': 1, 'id': 17140, 'name': 'Abigail "
 "Breslin', 'order': 0, 'profile_path': '/5zM4beIvrFKICiJXhQCqY3ORngR.jpg'}, "
 "{'cast_id': 2, 'character': 'Alexandra Rover', 'credit_id': "
 "'52fe43799251416c75011cb1', 'gender': 1, 'id': 1038, 'name': 'Jodie Foster', "
 "'order': 1, 'profile_path': '/eAIE6bnOQ8rm0f933gyeAQdIwrP.jpg'}, {'cast_id': "
 "3, 'character': 'Jack Rusoe / Alex Rover', 'credit_id': "
 "'52fe43799251416c75011cb5', 'gender': 2, 'id': 17276, 'name': 'Gerard "
 "Butler', 'order': 2, 'profile_path': '/i54XoxYieuff2w6MwyfwVUBvmR0.jpg'}, "
 "{'cast_id': 8, 'character': 'Captain', 'credit_..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 21, 'character': 'Johnny Rico', 'credit_id': "
 "'52fe4253c3a36847f80155a5', 'gender': 2, 'id': 27763, 'name': 'Casper Van "
 "Dien', 'order': 0, 'profile_path': '/ktJIgsilxxQeOvA9I789veHnDnt.jpg'}, "
 "{'cast_id': 22, 'character': 'Dizzy Flores', 'credit_id': "
 "'52fe4253c3a36847f80155a9', 'gender': 1, 'id': 2133, 'name': 'Dina Meyer', "
 "'order': 1, 'profile_path': '/a208ijs7X3u8lPzKWHeXSp3PiMd.jpg'}, {'cast_id': "
 "23, 'character': 'Carmen Iba√±ez', 'credit_id': '52fe4253c3a36847f80155ad', "
 "'gender': 1, 'id': 9205, 'name': 'Denise Richards', 'order': 2, "
 "'profile_path': '/r273Tmck64anm3uuccE8zfJD8da.jpg'}, {'cast_id': 24, "
 "'character': 'Private Ace Levy', 'credi..., key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...
parse_json_cache(("[{'cast_id': 0, 'character': 'Zhou Xiao Zhi', 'credit_id': "
 "'54064d4d0e0a2658de00e038', 'gender': 1, 'id': 145092, 'name': 'Zhou "
 "Dongyu', 'order': 0, 'profile_path': '/fmR9dO5cxrcwk5bjENU4eNITgLi.jpg'}, "
 "{'cast_id': 8, 'character': 'Lin Yi', 'credit_id': "
 "'54078e710e0a261896001f72', 'gender': 2, 'id': 1254211, 'name': 'Lin "
 "Gengxin', 'order': 1, 'profile_path': '/uo7e4jI7cD3oCiZmXP8vJPM515G.jpg'}, "
 "{'cast_id': 6, 'character': 'Tom', 'credit_id': '54064f120e0a2658f100dc46', "
 "'gender': 2, 'id': 1089502, 'name': 'Mike Sui', 'order': 2, 'profile_path': "
 "None}, {'cast_id': 7, 'character': 'Xiao Zhi', 'credit_id': "
 "'54064f270e0a2649e5002e12', 'gender': 0, 'id': 1173805, 'name': 'Zhang "
 "Zi-Feng', 'order': 3, 'profile_path': '/dC4zN3x9LKArz7zOcijb5A7iqDC.jpg'}]"), key='name')
_________________________________________________parse_json_cache - 0.0s, 0.0min
________________________________________________________________________________
[Memory] Calling __main__--content-drive-MyDrive-M2_Project-<ipython-input-7067ccf78c42>.parse_json_cache...

0       Rob Corddry,Craig Robinson,Clark Duke,Adam Sco...
1       Anne Hathaway,Julie Andrews,H√©ctor Elizondo,J...
2       Miles Teller,J.K. Simmons,Melissa Benoist,Aust...
3       Vidya Balan,Nawazuddin Siddiqui,Parambrata Cha...
4       Kim Kang-woo,Jo Jae-hyeon,Park Si-yeon,Kim Joo...
                              ...
2995    Tom Berenger,William McNamara,–≠—Ä–∏–∫–∞ –≠–ª–...
2996    Mira Barkhammar,Mira Grosin,Liv LeMoyne,David ...
2997    Geena Davis,Samuel L. Jackson,Yvonne Zima,Crai...
2998    Ben Stiller,Jennifer Aniston,Philip Seymour Ho...
2999    Taylor Lautner,Lily Collins,Alfred Molina,Jaso...
Name: cast, Length: 15000, dtype: object

In [ ]:
%time read_imdb_data.cast.apply(parse_json_cache,key = 'name') # load from the saved cache

CPU times: user 17.1 s, sys: 6.09 s, total: 23.2 s
Wall time: 1min 58s

0       Rob Corddry,Craig Robinson,Clark Duke,Adam Sco...
1       Anne Hathaway,Julie Andrews,H√©ctor Elizondo,J...
2       Miles Teller,J.K. Simmons,Melissa Benoist,Aust...
3       Vidya Balan,Nawazuddin Siddiqui,Parambrata Cha...
4       Kim Kang-woo,Jo Jae-hyeon,Park Si-yeon,Kim Joo...
                              ...
2995    Tom Berenger,William McNamara,–≠—Ä–∏–∫–∞ –≠–ª–...
2996    Mira Barkhammar,Mira Grosin,Liv LeMoyne,David ...
2997    Geena Davis,Samuel L. Jackson,Yvonne Zima,Crai...
2998    Ben Stiller,Jennifer Aniston,Philip Seymour Ho...
2999    Taylor Lautner,Lily Collins,Alfred Molina,Jaso...
Name: cast, Length: 15000, dtype: object

### Writing data

In [ ]:
os.getcwd()

'/content/drive/MyDrive/M2_Project'

In [ ]:
# Writing to csv
read_imdb_data.to_csv('read_imdb_data_w.csv', index=False) # Index = False to avoid the index.

In [ ]:
# Writing to excel

In [ ]:
# df
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35]}
df = pd.DataFrame(data)
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [ ]:
# df2
data = {'Name': ['John', 'Hop', 'Titan'],
        'Age': [40, 35, 55]}
df2 = pd.DataFrame(data)
df2

    Name  Age
0   John   40
1    Hop   35
2  Titan   55

In [ ]:
with pd.ExcelWriter('dataframe.xlsx') as writer:
    df.to_excel(writer, sheet_name='df')
    df2.to_excel(writer, sheet_name='df2', index = False)

In [ ]:
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [ ]:
# Writing to Json

# Convert DataFrame to JSON with 'records' orient
json_str = df.to_json(orient='records')

print(json_str)

[{"Name":"Alice","Age":25},{"Name":"Bob","Age":30},{"Name":"Charlie","Age":35}]

In [ ]:
json_str = df.to_json(orient='columns')

print(json_str)

{"Name":{"0":"Alice","1":"Bob","2":"Charlie"},"Age":{"0":25,"1":30,"2":35}}

In [ ]:
# Convert DataFrame to HTML
html_table = df.to_html(index=False)

# Print or save the HTML table
print(html_table)

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>Name</th>
      <th>Age</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Alice</td>
      <td>25</td>
    </tr>
    <tr>
      <td>Bob</td>
      <td>30</td>
    </tr>
    <tr>
      <td>Charlie</td>
      <td>35</td>
    </tr>
  </tbody>
</table>